import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../dist/server/index.js';
const mobile='09123456789';
// Transactional SQLite adapter for the exact D1 prepared statements used in production.
function database(){
 const raw=new DatabaseSync(':memory:');raw.exec('PRAGMA foreign_keys=ON');
 for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())raw.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
 class Statement{constructor(q,args=[]){this.q=q;this.args=args}bind(...args){return new Statement(this.q,args)}async first(){return raw.prepare(this.q).get(...this.args)??null}async all(){return {results:raw.prepare(this.q).all(...this.args)}}async run(){return {meta:{changes:Number(raw.prepare(this.q).run(...this.args).changes)}}}}
 return {raw,prepare:q=>new Statement(q),async batch(items){raw.exec('BEGIN');try{const results=items.map(s=>{const q=raw.prepare(s.q);return q.columns().length?{results:q.all(...s.args)}:{meta:{changes:Number(q.run(...s.args).changes)}}});raw.exec('COMMIT');return results}catch(e){raw.exec('ROLLBACK');throw e}}};
}
async function fixture(){
 const DB=database(),env={DB,DEMO_MODE:'true'},pending=[];
 async function call(path,method='GET',body,session,overrides={}){const response=await worker.fetch(new Request('https://test.local'+path,{method,headers:{'content-type':'application/json',...(session?{cookie:session}:{})},body:body===undefined?undefined:JSON.stringify(body)}),{...env,...overrides},{waitUntil:p=>pending.push(p)});const data=await response.json();await Promise.all(pending.splice(0));return {status:response.status,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}
 async function setup(name){const r=await call('/api/setup','POST',{cafeName:name,city:'تهران',branchName:'مرکزی',ownerMobile:mobile,ownerName:'مالک'});assert.equal(r.status,201);const slug=r.data.cafe.slug;const b=r.data.branches[0].id;DB.raw.prepare('UPDATE branch_settings SET sms_confirmation_enabled=0,sms_reminder_enabled=0 WHERE branch_id=?').run(b);return {slug,b,base:`/api/cafes/${slug}/branches/main`,table:b+':t1'}}
 const a=await setup('کافه الف'),b=await setup('کافه دوم');
 async function login(cafe=a){const r=await call('/api/auth/request','POST',{cafeSlug:cafe.slug,mobile});assert.equal(r.status,200);const v=await call('/api/auth/verify','POST',{cafeSlug:cafe.slug,mobile,code:r.data.demoCode,challengeId:r.data.challengeId});assert.equal(v.status,200);return v.cookie}
 const booking=(time='12:00',date='2090-01-02',table=a.table)=>({customerName:'مهمان',mobile,partySize:2,date,time,tableIds:[table]});
 return {DB,call,a,b,login,booking};
}
test('migrations and foreign keys',async()=>{const {DB}=await fixture();assert.deepEqual(DB.raw.prepare('PRAGMA foreign_key_check').all(),[])});
test('normal booking, tracking, cancellation and capacity release',async()=>{const {call,a,booking}=await fixture();const r=await call(a.base+'/reservations','POST',booking());assert.equal(r.status,201);assert.equal(r.data.status,'confirmed');const url='/api/reservations/'+r.data.trackingCode;assert.equal((await call(url+'?mobile='+mobile)).status,200);assert.equal((await call(url+'/cancel','POST',{mobile})).status,200);assert.equal((await call(a.base+'/reservations','POST',booking())).status,201)});
test('two simultaneous requests have one winner',async()=>{const {call,a,booking}=await fixture();const rs=await Promise.all([call(a.base+'/reservations','POST',booking()),call(a.base+'/reservations','POST',booking())]);assert.deepEqual(rs.map(r=>r.status).sort(),[201,409])});
test('off-grid overlapping start is rejected in either order',async()=>{for(const times of [['12:00','12:15'],['12:15','12:00']]){const {call,a,booking}=await fixture();assert.equal((await call(a.base+'/reservations','POST',booking(times[0]))).status,201);assert.equal((await call(a.base+'/reservations','POST',booking(times[1]))).status,409)}});
test('exact duration + buffer endpoint is bookable',async()=>{const {call,a,booking}=await fixture();await call(a.base+'/reservations','POST',booking());assert.equal((await call(a.base+'/reservations','POST',booking('13:44'))).status,409);assert.equal((await call(a.base+'/reservations','POST',booking('13:45'))).status,201)});
test('changed slot interval does not hide an existing reservation',async()=>{const {call,a,booking,DB}=await fixture();await call(a.base+'/reservations','POST',booking('12:15'));DB.raw.prepare('UPDATE branch_settings SET slot_interval=60 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/availability?date=2090-01-02&party_size=2');assert.equal(r.data.slots.find(s=>s.time==='13:00').tableIds.includes(a.table),false)});
test('past and impossible calendar dates are rejected',async()=>{const {call,a,booking}=await fixture();assert.equal((await call(a.base+'/reservations','POST',booking('12:00','2020-01-01'))).status,409);assert.equal((await call(a.base+'/reservations','POST',booking('12:00','2090-02-31'))).status,400);const slots=await call(a.base+'/availability?date=2020-01-01&party_size=2');assert.equal(slots.data.slots.some(s=>s.available),false)});
test('dirty and inactive tables are neither advertised nor bookable',async()=>{for(const state of ['dirty','inactive']){const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE cafe_tables SET operational_status=? WHERE id=?').run(state,a.table);assert.equal((await call(a.base+'/reservations','POST',booking())).status,400);const r=await call(a.base+'/availability?date=2090-01-02&party_size=2');assert.equal(r.data.slots.some(s=>s.tableIds.includes(a.table)),false)}});
test('indoor and yard selection survives save and booking; hidden areas reject direct requests',async()=>{const {call,a,booking,login}=await fixture();const owner=await login();let map=await call(a.base+'/map');map.data.spaceMode='both';map.data.areas.push({id:'yard',name:'حیاط',kind:'outdoor'});map.data.tables.push({id:'yard1',area:'yard',name:'میز حیاط',capacity:4,shape:'round',reservable:true,x:100,y:100});assert.equal((await call(a.base+'/map','PUT',{map:map.data},owner)).status,200);assert.equal((await call(a.base+'/reservations','POST',booking('12:00','2090-01-02',a.b+':yard1'))).status,201);map.data.spaceMode='indoor';await call(a.base+'/map','PUT',{map:map.data},owner);assert.equal((await call(a.base+'/reservations','POST',booking('12:00','2090-01-03',a.b+':yard1'))).status,400)});
test('owner cannot read or mutate another café',async()=>{const {call,a,b,login}=await fixture();const owner=await login(a);for(const [path,method,body] of [[b.base+'/settings','PUT',{}],[b.base+'/map','PUT',{map:{}}],[b.base+'/reservations?date=2090-01-02','GET'],[b.base+'/operations','GET'],[b.base+'/notifications','GET'],[b.base+'/map/analyze','GET']])assert.equal((await call(path,method,body,owner)).status,403)});
test('setup never selects the most recently created cafe',async()=>{const {call,a,login}=await fixture();assert.equal((await call('/api/setup')).data.configured,false);assert.equal((await call('/api/setup?cafe='+a.slug)).data.cafe.slug,a.slug);assert.equal((await call('/api/setup','GET',undefined,await login(a))).data.cafe.slug,a.slug)});
test('owner branch creation and profile editing stay in own cafe',async()=>{const {call,a,b,login}=await fixture();const owner=await login(a);const r=await call('/api/branches','POST',{name:'شعبه تازه',city:'تهران'},owner);assert.equal(r.status,201);assert.equal(r.data.cafe.slug,a.slug);assert.equal((await call('/api/setup?cafe='+b.slug)).data.branches.length,1);assert.equal((await call('/api/setup','PATCH',{cafeName:'ویرایش',city:'تهران',branchName:'مرکزی',branchSlug:'main'},owner)).data.cafe.slug,a.slug)});
test('OTP is cafe-bound, single use, and bootstrap cannot be hijacked',async()=>{const {call,a,b}=await fixture();assert.equal((await call('/api/auth/request','POST',{cafeSlug:a.slug,mobile:'09120000000'})).status,403);const r=await call('/api/auth/request','POST',{cafeSlug:a.slug,mobile});const body={cafeSlug:b.slug,mobile,code:r.data.demoCode,challengeId:r.data.challengeId};assert.equal((await call('/api/auth/verify','POST',body)).status,400);body.cafeSlug=a.slug;const rs=await Promise.all([call('/api/auth/verify','POST',body),call('/api/auth/verify','POST',body)]);assert.deepEqual(rs.map(r=>r.status).sort(),[200,400])});
test('production does not reveal a demo OTP when SMS config is missing',async()=>{const {call,a}=await fixture();const r=await call('/api/auth/request','POST',{cafeSlug:a.slug,mobile},undefined,{DEMO_MODE:undefined});assert.equal(r.status,503);assert.equal(r.data.demoCode,undefined)});
test('customer cannot assign staff-only reservation status',async()=>{const {call,a,booking,DB}=await fixture();const r=await call(a.base+'/reservations','POST',booking());const denied=await call('/api/reservations/'+r.data.trackingCode,'PATCH',{mobile,status:'completed'});assert.equal(denied.status,405);assert.equal(DB.raw.prepare('SELECT status FROM reservations WHERE id=?').get(r.data.reservation.id).status,'confirmed')});
test('operational updates obey hours, conflict, blocked tables and terminal states',async()=>{const {call,a,booking,login}=await fixture();const owner=await login();const r=await call(a.base+'/reservations','POST',booking());const path=a.base+'/operations/reservations/'+r.data.trackingCode;assert.equal((await call(path,'PATCH',{time:'23:30'},owner)).status,409);await call(a.base+'/reservations','POST',booking('15:00'));assert.equal((await call(path,'PATCH',{time:'15:15'},owner)).status,409);assert.equal((await call(path,'PATCH',{status:'completed'},owner)).status,200);assert.equal((await call(path,'PATCH',{status:'confirmed'},owner)).status,409)});
test('cancelled deposit cannot be paid or resurrected',async()=>{const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/reservations','POST',booking());const path='/api/reservations/'+r.data.trackingCode;assert.equal((await call(path+'/cancel','POST',{mobile})).status,200);assert.equal((await call(path+'/pay','POST',{mobile})).status,409);assert.equal(DB.raw.prepare('SELECT status FROM reservations WHERE id=?').get(r.data.reservation.id).status,'cancelled')});
test('concurrent demo payment is idempotent and retains table allocation',async()=>{const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/reservations','POST',booking());const path='/api/reservations/'+r.data.trackingCode+'/pay';const paid=await Promise.all([call(path,'POST',{mobile}),call(path,'POST',{mobile})]);assert.deepEqual(paid.map(r=>r.status),[200,200]);assert.equal(DB.raw.prepare('SELECT count(*) AS n FROM payment_transactions').get().n,1);assert.equal((await call(a.base+'/reservations','POST',booking())).status,409)});
test('payment respects manual confirmation and production mode',async()=>{const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1,auto_confirm=0 WHERE branch_id=?').run(a.b);assert.equal((await call(a.base+'/reservations','POST',booking(),undefined,{DEMO_MODE:undefined})).status,503);const r=await call(a.base+'/reservations','POST',booking());const paid=await call('/api/reservations/'+r.data.trackingCode+'/pay','POST',{mobile});assert.equal(paid.status,200);assert.equal(paid.data.status,'pending');assert.equal(paid.data.payment.status,'paid')});
test('expired unpaid holds release capacity without deleting a paid booking',async()=>{const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/reservations','POST',booking());DB.raw.prepare("UPDATE reservations SET payment_due_at='2000-01-01' WHERE id=?").run(r.data.reservation.id);assert.equal((await call(a.base+'/reservations','POST',booking())).status,201);assert.equal((await call('/api/reservations/'+r.data.trackingCode+'/pay','POST',{mobile})).status,409)});
test('database rejects cross-cafe reservation-table associations',async()=>{const {call,a,b,booking,DB}=await fixture();const r=await call(a.base+'/reservations','POST',booking());assert.throws(()=>DB.raw.prepare('INSERT INTO reservation_tables(reservation_id,table_id) VALUES (?,?)').run(r.data.reservation.id,b.table),/invalid_table_scope/)});
test('repeat refunds cannot create duplicate refund records',async()=>{const {call,a,booking,DB,login}=await fixture();const owner=await login();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/reservations','POST',booking());await call('/api/reservations/'+r.data.trackingCode+'/pay','POST',{mobile});const transaction=DB.raw.prepare("SELECT id FROM payment_transactions WHERE type='payment'").get();const results=await Promise.all([call('/api/payments/'+transaction.id+'/refund','POST',{},owner),call('/api/payments/'+transaction.id+'/refund','POST',{},owner)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal(DB.raw.prepare("SELECT count(*) AS n FROM payment_transactions WHERE type='refund'").get().n,1)});
test('cancellation and payment races leave a consistent allocation',async()=>{const {call,a,booking,DB}=await fixture();DB.raw.prepare('UPDATE branch_settings SET deposit_enabled=1 WHERE branch_id=?').run(a.b);const r=await call(a.base+'/reservations','POST',booking());const path='/api/reservations/'+r.data.trackingCode;await Promise.all([call(path+'/cancel','POST',{mobile}),call(path+'/pay','POST',{mobile})]);const row=DB.raw.prepare('SELECT status,payment_status FROM reservations WHERE id=?').get(r.data.reservation.id);assert.equal(row.status,'cancelled');assert.equal((await call(a.base+'/reservations','POST',booking())).status,201)});
test('staff status updates with unchanged table and past start remain usable',async()=>{const {call,a,booking,DB,login}=await fixture();const owner=await login();const r=await call(a.base+'/reservations','POST',booking());DB.raw.prepare("UPDATE reservations SET reserved_at='2020-01-01T12:00' WHERE id=?").run(r.data.reservation.id);const path=a.base+'/operations/reservations/'+r.data.trackingCode;assert.equal((await call(path,'PATCH',{date:'2020-01-01',time:'12:00',tableIds:[a.table],status:'arrived'},owner)).status,200);assert.equal((await call(path,'PATCH',{date:'2020-01-01',time:'12:15',tableIds:[a.table],status:'arrived'},owner)).status,409)});
test('an inactive session and branch-limited staff cannot cross branches',async()=>{const {call,a,DB,login}=await fixture();const owner=await login();DB.raw.prepare("UPDATE staff_members SET role='reception',branch_id=? WHERE cafe_id=(SELECT cafe_id FROM branches WHERE id=?)").run(a.b,a.b);assert.equal((await call(a.base+'/operations','GET',undefined,owner)).status,200);assert.equal((await call(a.base+'/settings','PUT',{},owner)).status,403);DB.raw.prepare('UPDATE staff_members SET active=0').run();assert.equal((await call(a.base+'/operations','GET',undefined,owner)).status,403)});
