import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../web/app.js',import.meta.url),'utf8');
function fn(name){const start=source.indexOf('function '+name+'('),end=source.indexOf('\nfunction ',start+1);const wiring=source.indexOf('\ndocument.querySelector',start+1);return source.slice(start,wiring>=0&&(end<0||wiring<end)?wiring:end)}
test('furniture has exactly one visual seat per capacity for every supported shape',()=>{const c=vm.createContext({});vm.runInContext(fn('tableFurniture'),c);for(const shape of ['round','square','rect'])for(const capacity of [1,2,4,6,8,20]){const markup=c.tableFurniture({shape,capacity});assert.equal((markup.match(/class="furniture-chair"/g)||[]).length,capacity);assert.ok(!markup.includes('NaN'))}});
test('undo restores table identity, coordinates and areas; a new edit drops redo',()=>{const controls={};const c=vm.createContext({mapHistory:[],mapHistoryIndex:-1,cafeMap:{areas:[{id:'main'}],tables:[{id:'existing-booked-table',x:20,y:30}]},activeArea:'main',selectedId:null,dirty:false,document:{querySelector:key=>controls[key]??=( {})},visibleAreas:()=>[{id:'main'}],renderEditor:()=>{}});for(const name of ['resetMapHistory','recordMapHistory','syncHistoryButtons','travelMapHistory'])vm.runInContext(fn(name),c);c.resetMapHistory();c.cafeMap.tables[0].x=300;c.recordMapHistory();c.travelMapHistory(-1);assert.equal(c.cafeMap.tables[0].x,20);assert.equal(c.cafeMap.tables[0].id,'existing-booked-table');c.travelMapHistory(1);assert.equal(c.cafeMap.tables[0].x,300);c.travelMapHistory(-1);c.cafeMap.tables[0].y=90;c.recordMapHistory();assert.equal(c.mapHistory.length,2);assert.equal(controls['#mapRedo'].disabled,true)});
test('a large room fits mobile without changing its world dimensions',()=>{const c=vm.createContext({});vm.runInContext(fn('fitFloorZoom'),c);const z=c.fitFloorZoom({width:4000,height:3000},320,360);assert.ok(4000*z<=320-64);assert.ok(3000*z<=360-64);assert.ok(z>0)});
test('gesture pan suppresses table activation, but a tap does not',()=>{const handlers={},wrap={scrollLeft:100,scrollTop:80,classList:{add(){},remove(){}},addEventListener(name,fn){handlers[name]=fn},hasPointerCapture(){return false},setPointerCapture(){},releasePointerCapture(){}},c=vm.createContext({Date,Map,Math});vm.runInContext(fn('setupFloorGestures'),c);c.setupFloorGestures(wrap,{},()=>1,()=>{});const e=(x,y)=>({button:0,pointerId:1,clientX:x,clientY:y,target:{closest(){return null}},preventDefault(){},stopImmediatePropagation(){}});handlers.pointerdown(e(100,100));handlers.pointerup(e(100,100));let blocked=false;handlers.click({...e(100,100),stopImmediatePropagation(){blocked=true}});assert.equal(blocked,false);handlers.pointerdown(e(100,100));handlers.pointermove(e(150,130));handlers.pointerup(e(150,130));handlers.click({...e(150,130),stopImmediatePropagation(){blocked=true}});assert.equal(blocked,true);assert.equal(wrap.scrollLeft,50);assert.equal(wrap.scrollTop,50)});
