import { appJs, editorCss, heroBase64, page, paymentsCss, saasCss, saasJs, saasPage, stylesCss } from "./site-content.js";

const jsonHeaders={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const textTypes={"/":"text/html; charset=utf-8","/index.html":"text/html; charset=utf-8","/styles.css":"text/css; charset=utf-8","/editor.css":"text/css; charset=utf-8","/payments.css":"text/css; charset=utf-8","/app.js":"text/javascript; charset=utf-8","/saas-admin":"text/html; charset=utf-8","/saas-admin.css":"text/css; charset=utf-8","/saas-admin.js":"text/javascript; charset=utf-8"};
const safeSlug=value=>/^[a-z0-9-]{1,64}$/.test(value||"");
const idPart=value=>String(value||"").replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,80);
const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:jsonHeaders});
const replyWithHeaders=(data,status,headers={})=>new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...headers}});
const pad=n=>String(n).padStart(2,"0");
const defaultSettings={reservationsEnabled:true,autoConfirm:true,reservationDuration:90,maxPartySize:8,customerNotice:"",bufferMinutes:15,slotInterval:30,smsConfirmationEnabled:true,smsReminderEnabled:true,smsReminderMinutes:120,depositEnabled:false,depositMode:"fixed",depositAmountRials:2000000,depositPeakOnly:false,depositPeakStart:"18:00",depositPeakEnd:"22:00",paymentDeadlineMinutes:15,refundPolicy:"Deposits are fully refundable up to two hours before arrival."};
const subscriptionUnitPriceRials=4900000;
const subscriptionOffer={id:"standard",name:"Mizo all-access",features:["All Mizo features","Flat price per active branch","SMS billed by usage"]};
const defaultHours=()=>Array.from({length:7},(_,weekday)=>({weekday,openTime:"10:00",closeTime:"23:00",closed:false}));
const starterMap={spaceMode:"indoor",areas:[{id:"main",name:"Main room",kind:"indoor"}],tables:[{id:"t1",area:"main",name:"Table 1",shape:"round",capacity:2,x:655,y:62,reservable:true},{id:"t2",area:"main",name:"Table 2",shape:"round",capacity:2,x:505,y:60,reservable:true},{id:"t3",area:"main",name:"Table 3",shape:"rect",capacity:4,x:345,y:68,reservable:true},{id:"t4",area:"main",name:"Table 4",shape:"square",capacity:2,x:620,y:230,reservable:true},{id:"t5",area:"main",name:"Table 5",shape:"round",capacity:2,x:430,y:235,reservable:true}]};

function decodeBase64(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
function normalizeDigits(value){return String(value||"").replace(/[0-9]/g,d=>String("0123456789".indexOf(d))).replace(/[٠-٩]/g,d=>String("0123456789".indexOf(d)))}
function normalizeMobile(value){let mobile=normalizeDigits(value).replace(/[^0-9+]/g,"");if(mobile.startsWith("+98"))mobile="0"+mobile.slice(3);if(mobile.startsWith("98"))mobile="0"+mobile.slice(2);return /^09\d{9}$/.test(mobile)?mobile:null}
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value||"")&&!Number.isNaN(new Date(`${value}T12:00:00Z`).getTime())}
function validTime(value){if(!/^\d{2}:\d{2}$/.test(value||""))return false;const [h,m]=value.split(":").map(Number);return h<24&&m<60}
function minutes(value){const [h,m]=value.split(":").map(Number);return h*60+m}
function timeAt(date,total){const dayOffset=Math.floor(total/1440),left=((total%1440)+1440)%1440,d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+dayOffset);return `${d.toISOString().slice(0,10)}T${pad(Math.floor(left/60))}:${pad(left%60)}`}
function lockTimes(date,time,duration,buffer,step){const start=minutes(time),count=Math.ceil((duration+buffer)/step);return Array.from({length:count},(_,i)=>timeAt(date,start+i*step))}
function trackingCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=new Uint8Array(6);crypto.getRandomValues(bytes);return `RMA-${Array.from(bytes,b=>chars[b%chars.length]).join("")}`}
function randomId(prefix){return `${prefix}:${crypto.randomUUID()}`}
async function sha256(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("")}
function cookieValue(request,name){const cookie=request.headers.get("cookie")||"";for(const part of cookie.split(";")){const [key,...value]=part.trim().split("=");if(key===name)return decodeURIComponent(value.join("="))}return ""}
async function sessionStaff(db,request){const token=cookieValue(request,"mizo_session");if(!token)return null;const tokenHash=await sha256(token),now=Date.now();return db.prepare("SELECT s.id,s.cafe_id,s.branch_id,s.mobile,s.name,s.role,s.active,ss.id AS session_id FROM staff_sessions ss JOIN staff_members s ON s.id=ss.staff_id WHERE ss.token_hash=? AND ss.expires_at>? AND s.active=1 LIMIT 1").bind(tokenHash,now).first()}
function staffPublic(row){return {id:row.id,name:row.name,mobile:row.mobile,role:row.role,active:Boolean(row.active),branchId:row.branch_id||null}}
function roleLabel(role){return ({owner:"Café owner",branch_manager:"Branch manager",reception:"Reception",barista:"Barista"})[role]||role}
const rolePermissions={owner:["dashboard.view","reservations.read","reservations.write","waitlist.read","waitlist.write","tables.write","settings.write","map.write","schedule.write","messages.read","messages.write","reports.read","loyalty.read","loyalty.write","payments.read","payments.write","staff.manage","branches.manage","cafe.manage"],branch_manager:["dashboard.view","reservations.read","reservations.write","waitlist.read","waitlist.write","tables.write","settings.write","map.write","schedule.write","messages.read","messages.write","reports.read","loyalty.read","loyalty.write","payments.read","payments.write"],reception:["dashboard.view","reservations.read","reservations.write","waitlist.read","waitlist.write","messages.read","loyalty.read","payments.read"],barista:["dashboard.view","tables.write"]};
function permissionsFor(role){return rolePermissions[role]||[]}
function hasPermission(staff,permission){return Boolean(staff&&permissionsFor(staff.role).includes(permission))}
function staffSessionPublic(row){return {...staffPublic(row),roleLabel:roleLabel(row.role),permissions:permissionsFor(row.role)}}
function canUseBranch(staff,branch){return staff?.role==="owner"||staff?.branch_id===branch?.id}
function secureCode(){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);return String(100000+(bytes[0]%900000))}
async function sendOtp(env,mobile,code){if(!env.KAVENEGAR_API_KEY||!env.KAVENEGAR_TEMPLATE)return {mode:"demo"};const endpoint=`https://api.kavenegar.com/v1/${encodeURIComponent(env.KAVENEGAR_API_KEY)}/verify/lookup.json?receptor=${encodeURIComponent(mobile)}&token=${encodeURIComponent(code)}&template=${encodeURIComponent(env.KAVENEGAR_TEMPLATE)}`,response=await fetch(endpoint,{method:"POST"});if(!response.ok)throw new Error("kavenegar_failed");return {mode:"kavenegar"}}
function subtractLocalMinutes(value,amount){const date=new Date(`${value}:00Z`);date.setUTCMinutes(date.getUTCMinutes()-amount);return date.toISOString().slice(0,16)}
function maskMobile(mobile){return mobile?`${mobile.slice(0,4)}***${mobile.slice(-4)}`:"—"}
async function sendReservationSms(env,kind,mobile,trackingCode,time,branchName){const template=kind==="confirmation"?env.KAVENEGAR_CONFIRMATION_TEMPLATE:env.KAVENEGAR_REMINDER_TEMPLATE;if(!env.KAVENEGAR_API_KEY||!template)return {mode:"demo",messageId:null};const endpoint=`https://api.kavenegar.com/v1/${encodeURIComponent(env.KAVENEGAR_API_KEY)}/verify/lookup.json?receptor=${encodeURIComponent(mobile)}&token=${encodeURIComponent(trackingCode)}&token2=${encodeURIComponent(time)}&token3=${encodeURIComponent(branchName)}&template=${encodeURIComponent(template)}`,response=await fetch(endpoint,{method:"POST"});if(!response.ok)throw new Error(`kavenegar_${response.status}`);const data=await response.json().catch(()=>null);return {mode:"kavenegar",messageId:String(data?.return?.value||data?.entries?.[0]?.messageid||"")||null}}
function smsText(kind,reservation,branch){return kind==="confirmation"?`Booking ${reservation.trackingCode} at ${branch.name} for ${reservation.date} at ${reservation.time} was created.`:`Booking reminder ${reservation.trackingCode}: see you at ${branch.name} on ${reservation.date} at ${reservation.time}.`}
async function deliverSmsMessage(env,row){try{const delivery=await sendReservationSms(env,row.kind,row.mobile,row.tracking_code,row.reserved_at.slice(11,16),row.branch_name),status=delivery.mode==="demo"?"demo_sent":"sent",sentAt=new Date().toISOString();await env.DB.prepare("UPDATE sms_messages SET status=?,sent_at=?,provider=?,provider_message_id=?,error='' WHERE id=?").bind(status,sentAt,delivery.mode,delivery.messageId,row.id).run();return {status,provider:delivery.mode}}catch(error){console.error("reservation_sms_failed",error);await env.DB.prepare("UPDATE sms_messages SET status='failed',error=? WHERE id=?").bind(String(error?.message||"send_failed").slice(0,160),row.id).run();return {status:"failed",provider:"kavenegar"}}}
async function queueReservationMessages(env,branch,reservation,settings){if(!reservation.mobile)return {confirmation:"skipped",reminder:"skipped"};const createdAt=new Date().toISOString(),results={confirmation:"disabled",reminder:"disabled"};if(settings.smsConfirmationEnabled){const id=randomId("sms"),message=smsText("confirmation",reservation,branch);await env.DB.prepare("INSERT INTO sms_messages (id,branch_id,reservation_id,kind,mobile,customer_name,message,status,scheduled_at,sent_at,provider,provider_message_id,error,created_at) VALUES (?,?,?,?,?,?,?,'queued',?,NULL,'demo',NULL,'',?)").bind(id,branch.id,reservation.id,"confirmation",reservation.mobile,reservation.customerName,message,createdAt,createdAt).run();results.confirmation=(await deliverSmsMessage(env,{id,kind:"confirmation",mobile:reservation.mobile,tracking_code:reservation.trackingCode,reserved_at:`${reservation.date}T${reservation.time}`,branch_name:branch.name})).status}if(settings.smsReminderEnabled){const scheduledAt=subtractLocalMinutes(`${reservation.date}T${reservation.time}`,settings.smsReminderMinutes),id=randomId("sms"),message=smsText("reminder",reservation,branch);await env.DB.prepare("INSERT INTO sms_messages (id,branch_id,reservation_id,kind,mobile,customer_name,message,status,scheduled_at,sent_at,provider,provider_message_id,error,created_at) VALUES (?,?,?,?,?,?,?,'queued',?,NULL,'demo',NULL,'',?)").bind(id,branch.id,reservation.id,"reminder",reservation.mobile,reservation.customerName,message,scheduledAt,createdAt).run();results.reminder="queued"}return results}
async function processDueReminders(env,branchId=null){const now=tehranNow().key,condition=branchId?"AND m.branch_id=?":"",query=`SELECT m.id,m.kind,m.mobile,r.tracking_code,r.reserved_at,b.name AS branch_name FROM sms_messages m JOIN reservations r ON r.id=m.reservation_id JOIN branches b ON b.id=m.branch_id WHERE m.kind='reminder' AND m.status='queued' AND m.scheduled_at<=? AND r.status NOT IN ('cancelled','completed','no_show') ${condition} ORDER BY m.scheduled_at LIMIT 25`,statement=env.DB.prepare(query),result=branchId?await statement.bind(now,branchId).all():await statement.bind(now).all(),rows=result.results||[];let processed=0;for(const row of rows){const claimed=await env.DB.prepare("UPDATE sms_messages SET status='sending' WHERE id=? AND status='queued'").bind(row.id).run();if(!claimed.meta?.changes)continue;await deliverSmsMessage(env,row);processed++}return {processed}}
const outdoorAreaName=name=>/(Terrace|Courtyard|Outdoor area)/.test(String(name||""));
function normalizeMap(input){const areas=Array.isArray(input?.areas)?input.areas.slice(0,20):[],tables=Array.isArray(input?.tables)?input.tables.slice(0,200):[];const normalizedAreas=areas.map((area,index)=>({id:idPart(area.id)||`area-${index+1}`,name:String(area.name||`Area ${index+1}`).slice(0,60),kind:area.kind==="outdoor"?"outdoor":"indoor",sortOrder:index})),areaIds=new Set(normalizedAreas.map(area=>area.id));const normalizedTables=tables.filter(table=>areaIds.has(idPart(table.area))).map((table,index)=>({id:idPart(table.id)||`table-${index+1}`,area:idPart(table.area),name:String(table.name||`Table ${index+1}`).slice(0,60),shape:["round","square","rect"].includes(table.shape)?table.shape:"round",capacity:Math.max(1,Math.min(20,Number(table.capacity)||2)),x:Math.max(0,Math.min(820,Number(table.x)||0)),y:Math.max(0,Math.min(520,Number(table.y)||0)),reservable:Boolean(table.reservable)})),kinds=new Set(normalizedAreas.map(area=>area.kind)),derived=kinds.size>1?"both":(kinds.has("outdoor")?"outdoor":"indoor"),requested=["indoor","outdoor","both"].includes(input?.spaceMode)?input.spaceMode:derived,spaceMode=requested==="both"&&kinds.size<2?derived:requested;return {spaceMode,areas:normalizedAreas,tables:normalizedTables}}

async function analyzeMapImage(request,env){
  if(!env.OPENAI_API_KEY)return reply({error:"image_analysis_unavailable",message:"AI image analysis is not enabled. You can add tables manually in the map editor."},503);
  if(Number(request.headers.get("content-length")||0)>2200000)return reply({error:"image_too_large",message:"Use a smaller image and try again."},413);
  const body=await request.json(),image=body?.image;
  if(typeof image!=="string"||image.length>2100000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(image))return reply({error:"invalid_image",message:"Invalid or oversized image."},400);
  const schema={type:"object",additionalProperties:false,required:["tables","note"],properties:{note:{type:"string"},tables:{type:"array",items:{type:"object",additionalProperties:false,required:["x","y","shape","capacity","confidence"],properties:{x:{type:"number"},y:{type:"number"},shape:{type:"string",enum:["round","square","rect"]},capacity:{type:"integer"},confidence:{type:"string",enum:["high","medium","low"]}}}}}};
  const upstream=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:env.MAP_VISION_MODEL||"gpt-4.1-mini",store:false,max_output_tokens:1300,input:[{role:"user",content:[{type:"input_text",text:"Identify physical cafe dining tables in this overhead photo or floor plan. Return only tables clearly visible; do not infer missing tables, counters, chairs, plants or decor as tables. x and y are the center of each table as percentages 0..100 of full image width and height. shape round/square/rect, estimated seating capacity, and confidence. If unsuitable image return empty tables and short Persian note. Persian note should describe uncertainty briefly."},{type:"input_image",image_url:image,detail:"high"}]}],text:{format:{type:"json_schema",name:"cafe_map_draft",strict:true,schema}}})});
  if(!upstream.ok){console.error("map_vision_failed",upstream.status);return reply({error:"analysis_failed",message:"Image analysis failed. Try again."},502)}
  const output=await upstream.json(),raw=(output.output||[]).flatMap(item=>item.type==="message"?item.content||[]:[]).find(part=>part.type==="output_text")?.text;
  if(!raw)return reply({error:"analysis_empty",message:"No tables detected. Choose a clearer image."},422);
  let draft;try{draft=JSON.parse(raw)}catch{return reply({error:"analysis_invalid",message:"Invalid image analysis response. Try again."},502)}
  const tables=(Array.isArray(draft.tables)?draft.tables:[]).slice(0,60).filter(t=>Number.isFinite(t.x)&&Number.isFinite(t.y)&&t.x>=0&&t.x<=100&&t.y>=0&&t.y<=100).map(t=>({x:Math.round(t.x),y:Math.round(t.y),shape:["round","square","rect"].includes(t.shape)?t.shape:"round",capacity:Math.max(1,Math.min(20,Number(t.capacity)||2)),confidence:["high","medium","low"].includes(t.confidence)?t.confidence:"low"}));
  return reply({tables,note:String(draft.note||"").slice(0,180)})
}
function normalizeSettings(input){return {reservationsEnabled:input?.reservationsEnabled!==false,autoConfirm:input?.autoConfirm!==false,reservationDuration:[60,90,120].includes(Number(input?.reservationDuration))?Number(input.reservationDuration):90,maxPartySize:Math.max(1,Math.min(20,Number(input?.maxPartySize)||8)),customerNotice:String(input?.customerNotice||"").trim().slice(0,140),bufferMinutes:[0,15,30,45].includes(Number(input?.bufferMinutes))?Number(input.bufferMinutes):15,slotInterval:[15,30,60].includes(Number(input?.slotInterval))?Number(input.slotInterval):30,smsConfirmationEnabled:input?.smsConfirmationEnabled!==false,smsReminderEnabled:input?.smsReminderEnabled!==false,smsReminderMinutes:[60,120,180,360,1440].includes(Number(input?.smsReminderMinutes))?Number(input.smsReminderMinutes):120,depositEnabled:Boolean(input?.depositEnabled),depositMode:input?.depositMode==="per_person"?"per_person":"fixed",depositAmountRials:Math.max(100000,Math.min(100000000,Number(input?.depositAmountRials)||2000000)),depositPeakOnly:Boolean(input?.depositPeakOnly),depositPeakStart:validTime(input?.depositPeakStart)?input.depositPeakStart:"18:00",depositPeakEnd:validTime(input?.depositPeakEnd)?input.depositPeakEnd:"22:00",paymentDeadlineMinutes:[10,15,30].includes(Number(input?.paymentDeadlineMinutes))?Number(input.paymentDeadlineMinutes):15,refundPolicy:String(input?.refundPolicy||defaultSettings.refundPolicy).trim().slice(0,240)}}
async function branchRow(db,cafeSlug,branchSlug){return db.prepare("SELECT b.id,b.cafe_id,b.name,b.city,b.address,b.active,b.space_mode FROM branches b JOIN cafes c ON c.id=b.cafe_id WHERE c.slug=? AND b.slug=? AND b.active=1 LIMIT 1").bind(cafeSlug,branchSlug).first()}

async function readSetup(db){
  const cafe=await db.prepare("SELECT id,slug,name,created_at FROM cafes WHERE slug!='roma' ORDER BY created_at DESC LIMIT 1").first();
  if(!cafe)return {configured:false};
  const result=await db.prepare("SELECT id,slug,name,city,address,active FROM branches WHERE cafe_id=? ORDER BY updated_at,id").bind(cafe.id).all(),branches=result.results||[];
  return {configured:true,cafe:{slug:cafe.slug,name:cafe.name,structure:branches.length>1||cafe.slug.startsWith("multi-")?"multi":"single"},branches:branches.map(branch=>({id:branch.id,slug:branch.slug,name:branch.name,city:branch.city,address:branch.address,active:Boolean(branch.active)}))};
}
async function writeSetup(db,body,editing=false){
  const name=String(body.cafeName||"").trim().slice(0,80),city=String(body.city||"").trim().slice(0,60),branchName=String(body.branchName||"").trim().slice(0,80),address=String(body.address||"").trim().slice(0,180),structure=body.structure==="multi"?"multi":"single";
  if(name.length<2||city.length<2||branchName.length<2)return reply({error:"invalid_setup",message:"Enter the café, city, and branch names."},400);
  if(editing){
    const current=await readSetup(db);if(!current.configured)return reply({error:"setup_not_found"},404);
    const cafeId=`cafe:${current.cafe.slug}`,branch=current.branches.find(item=>item.slug===body.branchSlug)||current.branches[0];
    await db.batch([db.prepare("UPDATE cafes SET name=? WHERE id=?").bind(name,cafeId),db.prepare("UPDATE branches SET name=?,city=?,address=?,updated_at=? WHERE cafe_id=? AND slug=?").bind(branchName,city,address,new Date().toISOString(),cafeId,branch.slug)]);
    return reply(await readSetup(db));
  }
  const existing=await readSetup(db);if(existing.configured)return reply(existing);
  const token=crypto.randomUUID().replace(/-/g,"").slice(0,10),cafeSlug=`${structure==="multi"?"multi":"cafe"}-${token}`,branchSlug="main";
  await writeMap(db,cafeSlug,branchSlug,{cafeName:name,branchName,city,address,map:starterMap});
  await writeSettings(db,cafeSlug,branchSlug,{...defaultSettings,cafeName:name,branchName,city,address});
  const branch=await branchRow(db,cafeSlug,branchSlug);await writeSchedule(db,branch,{hours:defaultHours(),closures:[]});
  return reply(await readSetup(db),201);
}
async function createBranch(db,body){
  const current=await readSetup(db);if(!current.configured)return reply({error:"setup_required",message:"Set up your café first."},409);
  const name=String(body.name||"").trim().slice(0,80),city=String(body.city||"").trim().slice(0,60),address=String(body.address||"").trim().slice(0,180);
  if(name.length<2||city.length<2)return reply({error:"invalid_branch",message:"Enter a branch name and city."},400);
  const slug=`branch-${crypto.randomUUID().replace(/-/g,"").slice(0,10)}`;
  await writeMap(db,current.cafe.slug,slug,{cafeName:current.cafe.name,branchName:name,city,address,map:starterMap});
  await writeSettings(db,current.cafe.slug,slug,{...defaultSettings,cafeName:current.cafe.name,branchName:name,city,address});
  const branch=await branchRow(db,current.cafe.slug,slug);await writeSchedule(db,branch,{hours:defaultHours(),closures:[]});
  return reply(await readSetup(db),201);
}
async function updateBranch(db,slug,body){
  const current=await readSetup(db);if(!current.configured)return reply({error:"setup_required"},409);
  const branch=current.branches.find(item=>item.slug===slug);if(!branch)return reply({error:"branch_not_found",message:"Branch not found."},404);
  const name=String(body.name??branch.name).trim().slice(0,80),city=String(body.city??branch.city).trim().slice(0,60),address=String(body.address??branch.address).trim().slice(0,180),active=body.active!==false;
  if(name.length<2||city.length<2)return reply({error:"invalid_branch",message:"Enter a branch name and city."},400);
  if(!active&&branch.active&&current.branches.filter(item=>item.active).length===1)return reply({error:"last_active_branch",message:"At least one branch must stay active."},409);
  await db.prepare("UPDATE branches SET name=?,city=?,address=?,active=?,updated_at=? WHERE cafe_id=? AND slug=?").bind(name,city,address,active?1:0,new Date().toISOString(),`cafe:${current.cafe.slug}`,slug).run();
  return reply(await readSetup(db));
}
async function requestOtp(env,body){
  const mobile=normalizeMobile(body.mobile);if(!mobile)return reply({error:"invalid_mobile",message:"Enter a valid mobile number."},400);
  const setup=await readSetup(env.DB);if(!setup.configured)return reply({error:"setup_required",message:"Set up the café first."},409);
  const cafeId=`cafe:${setup.cafe.slug}`,now=Date.now(),hourAgo=now-3600000,demoMode=!env.KAVENEGAR_API_KEY||!env.KAVENEGAR_TEMPLATE,[staff,count,last,recent]=await Promise.all([env.DB.prepare("SELECT id,name,active FROM staff_members WHERE cafe_id=? AND mobile=? LIMIT 1").bind(cafeId,mobile).first(),env.DB.prepare("SELECT COUNT(*) AS count FROM staff_members WHERE cafe_id=?").bind(cafeId).first(),env.DB.prepare("SELECT created_at FROM otp_challenges WHERE mobile=? ORDER BY created_at DESC LIMIT 1").bind(mobile).first(),env.DB.prepare("SELECT COUNT(*) AS count FROM otp_challenges WHERE mobile=? AND created_at>?").bind(mobile,hourAgo).first()]);
  const requiresBootstrap=Number(count?.count||0)===0;if(!requiresBootstrap&&(!staff||!staff.active))return reply({error:"not_invited",message:"This number is not active on the staff list."},403);
  if(!demoMode&&last&&now-Number(last.created_at)<60000)return reply({error:"too_soon",message:"Wait one minute before requesting another code."},429);if(!demoMode&&Number(recent?.count||0)>=5)return reply({error:"rate_limited",message:"Too many requests. Try again later."},429);
  const code=secureCode(),salt=crypto.randomUUID(),codeHash=await sha256(`${salt}:${code}`),challengeId=randomId("otp"),expiresAt=now+120000;
  let delivery;try{delivery=await sendOtp(env,mobile,code)}catch(error){console.error("otp_delivery_failed",error);return reply({error:"sms_unavailable",message:"Could not send SMS. Try again."},503)}
  await env.DB.batch([env.DB.prepare("UPDATE otp_challenges SET consumed_at=? WHERE mobile=? AND consumed_at IS NULL").bind(now,mobile),env.DB.prepare("INSERT INTO otp_challenges (id,mobile,salt,code_hash,expires_at,attempts,consumed_at,created_at) VALUES (?,?,?,?,?,0,NULL,?)").bind(challengeId,mobile,salt,codeHash,expiresAt,now)]);
  return reply({challengeId,expiresIn:120,requiresBootstrap,delivery:delivery.mode,...(delivery.mode==="demo"?{demoCode:code}:{})});
}
async function verifyOtp(env,body){
  const mobile=normalizeMobile(body.mobile),code=normalizeDigits(body.code).replace(/\D/g,""),challenge=await env.DB.prepare("SELECT id,mobile,salt,code_hash,expires_at,attempts,consumed_at FROM otp_challenges WHERE id=? LIMIT 1").bind(String(body.challengeId||"")).first(),now=Date.now();
  if(!mobile||!challenge||challenge.mobile!==mobile||challenge.consumed_at||Number(challenge.expires_at)<now)return reply({error:"expired_code",message:"Code expired or invalid."},400);if(Number(challenge.attempts)>=5)return reply({error:"too_many_attempts",message:"Too many attempts."},429);await env.DB.prepare("UPDATE otp_challenges SET attempts=attempts+1 WHERE id=?").bind(challenge.id).run();if(await sha256(`${challenge.salt}:${code}`)!==challenge.code_hash)return reply({error:"wrong_code",message:"Incorrect code."},400);
  const setup=await readSetup(env.DB),cafeId=`cafe:${setup.cafe.slug}`;let staff=await env.DB.prepare("SELECT id,cafe_id,branch_id,mobile,name,role,active FROM staff_members WHERE cafe_id=? AND mobile=? LIMIT 1").bind(cafeId,mobile).first();if(!staff){const count=await env.DB.prepare("SELECT COUNT(*) AS count FROM staff_members WHERE cafe_id=?").bind(cafeId).first();if(Number(count?.count||0)>0)return reply({error:"not_invited",message:"This number is not on the café team."},403);const name=String(body.name||"Primary owner").trim().slice(0,70)||"Primary owner",id=randomId("staff"),stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO staff_members (id,cafe_id,branch_id,mobile,name,role,active,created_at,updated_at) VALUES (?,?,NULL,?,?, 'owner',1,?,?)").bind(id,cafeId,mobile,name,stamp,stamp).run();staff=await env.DB.prepare("SELECT id,cafe_id,branch_id,mobile,name,role,active FROM staff_members WHERE id=?").bind(id).first()}
  if(!staff.active)return reply({error:"staff_inactive",message:"This user's access was disabled."},403);const token=`${crypto.randomUUID()}${crypto.randomUUID()}`,tokenHash=await sha256(token),sessionId=randomId("session"),expiresAt=now+604800000;await env.DB.batch([env.DB.prepare("UPDATE otp_challenges SET consumed_at=? WHERE id=?").bind(now,challenge.id),env.DB.prepare("DELETE FROM staff_sessions WHERE staff_id=? AND expires_at<?").bind(staff.id,now),env.DB.prepare("INSERT INTO staff_sessions (id,staff_id,token_hash,expires_at,created_at,last_seen_at) VALUES (?,?,?,?,?,?)").bind(sessionId,staff.id,tokenHash,expiresAt,now,now)]);return replyWithHeaders({authenticated:true,staff:staffSessionPublic(staff)},200,{"set-cookie":`mizo_session=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=604800`});
}
async function listStaff(db,session){if(!hasPermission(session,"staff.manage"))return reply({error:"forbidden",message:"Only the café owner can view staff."},403);const result=await db.prepare("SELECT s.id,s.name,s.mobile,s.role,s.active,s.branch_id,b.name AS branch_name FROM staff_members s LEFT JOIN branches b ON b.id=s.branch_id WHERE s.cafe_id=? ORDER BY s.created_at").bind(session.cafe_id).all();return reply({staff:(result.results||[]).map(row=>({...staffPublic(row),roleLabel:roleLabel(row.role),branchName:row.branch_name||"All branches"}))})}
async function saveStaff(db,session,body,id=null){if(session.role!=="owner")return reply({error:"forbidden",message:"Only the café owner can change staff access."},403);const mobile=normalizeMobile(body.mobile),name=String(body.name||"").trim().slice(0,70),allowed=["owner","branch_manager","reception","barista"],role=allowed.includes(body.role)?body.role:"reception",branchId=role==="owner"?null:String(body.branchId||"")||null,active=body.active!==false,now=new Date().toISOString();if(!mobile||name.length<2||(!branchId&&role!=="owner"))return reply({error:"invalid_staff",message:"Staff details are incomplete."},400);if(id===session.id&&(!active||role!=="owner"))return reply({error:"self_lockout",message:"You cannot remove your own role or access."},409);if(branchId){const branch=await db.prepare("SELECT id FROM branches WHERE id=? AND cafe_id=? LIMIT 1").bind(branchId,session.cafe_id).first();if(!branch)return reply({error:"invalid_branch",message:"Invalid branch."},400)}try{if(id){const result=await db.prepare("UPDATE staff_members SET mobile=?,name=?,role=?,branch_id=?,active=?,updated_at=? WHERE id=? AND cafe_id=?").bind(mobile,name,role,branchId,active?1:0,now,id,session.cafe_id).run();if(!result.meta?.changes)return reply({error:"staff_not_found"},404)}else await db.prepare("INSERT INTO staff_members (id,cafe_id,branch_id,mobile,name,role,active,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?)").bind(randomId("staff"),session.cafe_id,branchId,mobile,name,role,now,now).run()}catch(error){console.error("staff_save_failed",error);return reply({error:"duplicate_mobile",message:"This number is already assigned to staff."},409)}return listStaff(db,session)}

function pricedSubscription(activeBranchCount){const count=Math.max(0,Number(activeBranchCount)||0);return {...subscriptionOffer,activeBranchCount:count,unitPriceRials:subscriptionUnitPriceRials,monthlyPriceRials:count*subscriptionUnitPriceRials}}
async function readSubscription(db,cafeId){const [row,branches,events]=await db.batch([db.prepare("SELECT cafe_id,enabled,plan,status,monthly_price_rials,trial_ends_at,current_period_ends_at,created_at,updated_at FROM saas_subscriptions WHERE cafe_id=? LIMIT 1").bind(cafeId),db.prepare("SELECT COUNT(*) AS count FROM branches WHERE cafe_id=? AND active=1").bind(cafeId),db.prepare("SELECT id,type,from_plan,to_plan,amount_rials,note,created_at FROM subscription_events WHERE cafe_id=? ORDER BY created_at DESC LIMIT 12").bind(cafeId)]),subscription=row.results?.[0],offer=pricedSubscription(branches.results?.[0]?.count);return {optional:true,enabled:Boolean(subscription?.enabled),plan:"standard",status:subscription?.status||"inactive",monthlyPriceRials:offer.monthlyPriceRials,activeBranchCount:offer.activeBranchCount,unitPriceRials:offer.unitPriceRials,offer,trialEndsAt:subscription?.trial_ends_at||null,currentPeriodEndsAt:subscription?.current_period_ends_at||null,events:(events.results||[]).map(item=>({id:item.id,type:item.type,fromPlan:item.from_plan,toPlan:item.to_plan,amountRials:item.amount_rials,note:item.note,createdAt:item.created_at}))}}
async function updateSubscription(db,session,body){if(session.role!=="owner")return reply({error:"forbidden",message:"Only the café owner can manage subscriptions."},403);const [currentRow,branchRow]=await db.batch([db.prepare("SELECT enabled,plan,status,trial_ends_at,current_period_ends_at FROM saas_subscriptions WHERE cafe_id=? LIMIT 1").bind(session.cafe_id),db.prepare("SELECT COUNT(*) AS count FROM branches WHERE cafe_id=? AND active=1").bind(session.cafe_id)]),current=currentRow.results?.[0],enabled=body.enabled===true,plan="standard",now=new Date().toISOString(),firstActivation=enabled&&!current,status=enabled?(firstActivation?"trial":(["trial","active","past_due"].includes(current?.status)&&current.status!=="inactive"?current.status:"past_due")):"inactive",trialEndsAt=firstActivation?new Date(Date.now()+14*86400000).toISOString():current?.trial_ends_at||null,price=pricedSubscription(branchRow.results?.[0]?.count).monthlyPriceRials,type=!enabled?"disabled":firstActivation?"activated":"updated",eventId=randomId("subevent");await db.batch([db.prepare("INSERT INTO saas_subscriptions (cafe_id,enabled,plan,status,monthly_price_rials,trial_ends_at,current_period_ends_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(cafe_id) DO UPDATE SET enabled=excluded.enabled,plan=excluded.plan,status=excluded.status,monthly_price_rials=excluded.monthly_price_rials,trial_ends_at=excluded.trial_ends_at,updated_at=excluded.updated_at").bind(session.cafe_id,enabled?1:0,plan,status,price,trialEndsAt,current?.current_period_ends_at||null,now,now),db.prepare("INSERT INTO subscription_events (id,cafe_id,type,from_plan,to_plan,amount_rials,note,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(eventId,session.cafe_id,type,current?.plan||null,plan,0,enabled?"Subscription settings changed by the café owner":"Subscription module disabled by the café owner",now)]);return reply(await readSubscription(db,session.cafe_id))}
async function renewSubscriptionDemo(db,session){if(session.role!=="owner")return reply({error:"forbidden"},403);const [currentRow,branchRow]=await db.batch([db.prepare("SELECT enabled,plan FROM saas_subscriptions WHERE cafe_id=? LIMIT 1").bind(session.cafe_id),db.prepare("SELECT COUNT(*) AS count FROM branches WHERE cafe_id=? AND active=1").bind(session.cafe_id)]),current=currentRow.results?.[0];if(!current?.enabled)return reply({error:"subscription_disabled",message:"Enable subscriptions first."},409);const plan="standard",price=pricedSubscription(branchRow.results?.[0]?.count).monthlyPriceRials,now=new Date().toISOString(),periodEnd=new Date(Date.now()+30*86400000).toISOString();await db.batch([db.prepare("UPDATE saas_subscriptions SET status='active',plan=?,monthly_price_rials=?,current_period_ends_at=?,updated_at=? WHERE cafe_id=?").bind(plan,price,periodEnd,now,session.cafe_id),db.prepare("INSERT INTO subscription_events (id,cafe_id,type,from_plan,to_plan,amount_rials,note,created_at) VALUES (?,?, 'payment_demo',?,?,?,'Demo payment recorded',?)").bind(randomId("subevent"),session.cafe_id,current.plan||null,plan,price,now)]);return reply(await readSubscription(db,session.cafe_id))}
async function requireSaasAdmin(db,request){const id=request.headers.get("oai-authenticated-user-id");if(!id)return null;const email=request.headers.get("oai-authenticated-user-email")||"",existing=await db.prepare("SELECT id FROM saas_admins WHERE id=? LIMIT 1").bind(id).first();if(existing){await db.prepare("UPDATE saas_admins SET email=?,last_seen_at=? WHERE id=?").bind(email,new Date().toISOString(),id).run();return {id,email}}const count=await db.prepare("SELECT COUNT(*) AS count FROM saas_admins").first();if(Number(count?.count||0)>0)return null;const now=new Date().toISOString();await db.prepare("INSERT INTO saas_admins (id,email,created_at,last_seen_at) VALUES (?,?,?,?)").bind(id,email,now,now).run();return {id,email}}
async function readSaasOverview(db){const result=await db.prepare("SELECT c.id,c.name,c.slug,COUNT(DISTINCT CASE WHEN b.active=1 THEN b.id END) AS branch_count,COALESCE(s.enabled,0) AS enabled,COALESCE(s.status,'inactive') AS status,s.trial_ends_at,s.current_period_ends_at,c.created_at FROM cafes c LEFT JOIN branches b ON b.cafe_id=c.id LEFT JOIN saas_subscriptions s ON s.cafe_id=c.id WHERE c.slug!='roma' GROUP BY c.id ORDER BY c.created_at DESC").all(),cafes=(result.results||[]).map(row=>{const offer=pricedSubscription(row.branch_count);return {id:row.id,name:row.name,slug:row.slug,branchCount:offer.activeBranchCount,enabled:Boolean(row.enabled),plan:"standard",status:row.status,unitPriceRials:offer.unitPriceRials,monthlyPriceRials:offer.monthlyPriceRials,trialEndsAt:row.trial_ends_at,currentPeriodEndsAt:row.current_period_ends_at,createdAt:row.created_at}});return {unitPriceRials:subscriptionUnitPriceRials,stats:{cafes:cafes.length,enabled:cafes.filter(item=>item.enabled).length,trials:cafes.filter(item=>item.status==="trial").length,active:cafes.filter(item=>item.status==="active").length,mrrRials:cafes.filter(item=>item.status==="active"&&item.enabled).reduce((sum,item)=>sum+item.monthlyPriceRials,0)},cafes}}
async function updateSaasAccount(db,body){const cafeId=String(body.cafeId||""),[cafeRow,currentRow,branchRow]=await db.batch([db.prepare("SELECT id FROM cafes WHERE id=? LIMIT 1").bind(cafeId),db.prepare("SELECT enabled,plan,status FROM saas_subscriptions WHERE cafe_id=? LIMIT 1").bind(cafeId),db.prepare("SELECT COUNT(*) AS count FROM branches WHERE cafe_id=? AND active=1").bind(cafeId)]),cafe=cafeRow.results?.[0],current=currentRow.results?.[0];if(!cafe)return reply({error:"cafe_not_found"},404);const plan="standard",enabled=body.enabled!==false,status=enabled&&["trial","active","past_due"].includes(body.status)?body.status:"inactive",price=pricedSubscription(branchRow.results?.[0]?.count).monthlyPriceRials,now=new Date().toISOString();await db.batch([db.prepare("INSERT INTO saas_subscriptions (cafe_id,enabled,plan,status,monthly_price_rials,trial_ends_at,current_period_ends_at,created_at,updated_at) VALUES (?,?,?,?,?,NULL,NULL,?,?) ON CONFLICT(cafe_id) DO UPDATE SET enabled=excluded.enabled,plan=excluded.plan,status=excluded.status,monthly_price_rials=excluded.monthly_price_rials,updated_at=excluded.updated_at").bind(cafeId,enabled?1:0,plan,status,price,now,now),db.prepare("INSERT INTO subscription_events (id,cafe_id,type,from_plan,to_plan,amount_rials,note,created_at) VALUES (?,?, 'saas_admin_update',?,?,?,?,?)").bind(randomId("subevent"),cafeId,current?.plan||null,plan,0,"Edited from the SaaS console",now)]);return reply(await readSaasOverview(db))}

async function readMap(db,cafeSlug,branchSlug){const branch=await branchRow(db,cafeSlug,branchSlug);if(!branch)return null;const [areasResult,tablesResult]=await db.batch([db.prepare("SELECT id,name,kind,sort_order FROM areas WHERE branch_id=? ORDER BY sort_order,id").bind(branch.id),db.prepare("SELECT t.id,t.area_id,t.name,t.shape,t.capacity,t.position_x,t.position_y,t.reservable,t.operational_status FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? ORDER BY t.name").bind(branch.id)]),prefix=`${branch.id}:`,areas=(areasResult.results||[]).map(row=>({id:String(row.id).replace(prefix,""),name:row.name,kind:row.kind==="outdoor"||outdoorAreaName(row.name)?"outdoor":"indoor"})),kinds=new Set(areas.map(area=>area.kind)),derived=kinds.size>1?"both":(kinds.has("outdoor")?"outdoor":"indoor"),spaceMode=["indoor","outdoor","both"].includes(branch.space_mode)?branch.space_mode:derived;return {branch:{slug:branchSlug,name:branch.name,city:branch.city,address:branch.address},spaceMode,areas,tables:(tablesResult.results||[]).map(row=>({id:String(row.id).replace(prefix,""),area:String(row.area_id).replace(prefix,""),name:row.name,shape:row.shape,capacity:row.capacity,x:row.position_x,y:row.position_y,reservable:Boolean(row.reservable),operationalStatus:row.operational_status||"available"}))}}
async function writeMap(db,cafeSlug,branchSlug,body){
  const map=normalizeMap(body.map),now=new Date().toISOString(),cafeId=`cafe:${cafeSlug}`,branchId=`branch:${cafeSlug}:${branchSlug}`,statements=[db.prepare("INSERT INTO cafes (id,slug,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,name=excluded.name").bind(cafeId,cafeSlug,String(body.cafeName||cafeSlug).slice(0,80),now),db.prepare("INSERT INTO branches (id,cafe_id,slug,name,city,address,space_mode,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,city=excluded.city,address=excluded.address,space_mode=excluded.space_mode,updated_at=excluded.updated_at").bind(branchId,cafeId,branchSlug,String(body.branchName||branchSlug).slice(0,80),String(body.city||"London").slice(0,60),String(body.address||"").slice(0,180),map.spaceMode,now)];
  const areaIds=new Set(map.areas.map(area=>area.id)),tableIds=new Set(map.tables.map(table=>table.id));if(!areaIds.size||areaIds.size!==map.areas.length||tableIds.size!==map.tables.length)return reply({error:"invalid_map",message:"Duplicate area or table ID. Reload the map."},400);
  const existing=await db.prepare("SELECT t.id,t.name,COUNT(rt.reservation_id) AS reservation_count FROM cafe_tables t JOIN areas a ON a.id=t.area_id LEFT JOIN reservation_tables rt ON rt.table_id=t.id WHERE a.branch_id=? GROUP BY t.id").bind(branchId).all();const protectedTable=(existing.results||[]).find(row=>Number(row.reservation_count)>0&&!tableIds.has(String(row.id).slice(branchId.length+1)));if(protectedTable)return reply({error:"table_has_reservations",message:`Table «${protectedTable.name}» has booking history and cannot be deleted. Disable it instead.`},409);
  for(const area of map.areas)statements.push(db.prepare("INSERT INTO areas (id,branch_id,name,kind,sort_order) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,kind=excluded.kind,sort_order=excluded.sort_order").bind(`${branchId}:${area.id}`,branchId,area.name,area.kind,area.sortOrder));
  for(const table of map.tables)statements.push(db.prepare("INSERT INTO cafe_tables (id,area_id,name,shape,capacity,position_x,position_y,reservable,operational_status,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET area_id=excluded.area_id,name=excluded.name,shape=excluded.shape,capacity=excluded.capacity,position_x=excluded.position_x,position_y=excluded.position_y,reservable=excluded.reservable,updated_at=excluded.updated_at").bind(`${branchId}:${table.id}`,`${branchId}:${table.area}`,table.name,table.shape,table.capacity,table.x,table.y,table.reservable?1:0,"available",now));
  if(map.tables.length){const keep=map.tables.map(t=>`${branchId}:${t.id}`),marks=keep.map(()=>"?").join(",");statements.push(db.prepare(`DELETE FROM cafe_tables WHERE id IN (SELECT t.id FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? AND t.id NOT IN (${marks}))`).bind(branchId,...keep))}else statements.push(db.prepare("DELETE FROM cafe_tables WHERE area_id IN (SELECT id FROM areas WHERE branch_id=?)").bind(branchId));
  if(map.areas.length){const keep=map.areas.map(a=>`${branchId}:${a.id}`),marks=keep.map(()=>"?").join(",");statements.push(db.prepare(`DELETE FROM areas WHERE branch_id=? AND id NOT IN (${marks})`).bind(branchId,...keep))}
  await db.batch(statements);return readMap(db,cafeSlug,branchSlug)
}
async function readSettings(db,cafeSlug,branchSlug){const row=await db.prepare("SELECT s.* FROM branch_settings s JOIN branches b ON b.id=s.branch_id JOIN cafes c ON c.id=b.cafe_id WHERE c.slug=? AND b.slug=? LIMIT 1").bind(cafeSlug,branchSlug).first();return row?{reservationsEnabled:Boolean(row.reservations_enabled),autoConfirm:Boolean(row.auto_confirm),reservationDuration:row.reservation_duration,maxPartySize:row.max_party_size,customerNotice:row.customer_notice,bufferMinutes:row.buffer_minutes,slotInterval:row.slot_interval,smsConfirmationEnabled:Boolean(row.sms_confirmation_enabled),smsReminderEnabled:Boolean(row.sms_reminder_enabled),smsReminderMinutes:row.sms_reminder_minutes,depositEnabled:Boolean(row.deposit_enabled),depositMode:row.deposit_mode,depositAmountRials:Number(row.deposit_amount_rials),depositPeakOnly:Boolean(row.deposit_peak_only),depositPeakStart:row.deposit_peak_start,paymentDeadlineMinutes:Number(row.payment_deadline_minutes),depositPeakEnd:row.deposit_peak_end,refundPolicy:row.refund_policy}:defaultSettings}
async function writeSettings(db,cafeSlug,branchSlug,body){const s=normalizeSettings(body),now=new Date().toISOString(),cafeId=`cafe:${cafeSlug}`,branchId=`branch:${cafeSlug}:${branchSlug}`;await db.batch([db.prepare("INSERT INTO cafes (id,slug,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,name=excluded.name").bind(cafeId,cafeSlug,String(body.cafeName||cafeSlug).slice(0,80),now),db.prepare("INSERT INTO branches (id,cafe_id,slug,name,city,address,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,city=excluded.city,address=excluded.address,updated_at=excluded.updated_at").bind(branchId,cafeId,branchSlug,String(body.branchName||branchSlug).slice(0,80),String(body.city||"London").slice(0,60),String(body.address||"").slice(0,180),now),db.prepare("INSERT INTO branch_settings (branch_id,reservations_enabled,auto_confirm,reservation_duration,max_party_size,customer_notice,buffer_minutes,slot_interval,sms_confirmation_enabled,sms_reminder_enabled,sms_reminder_minutes,deposit_enabled,deposit_mode,deposit_amount_rials,deposit_peak_only,deposit_peak_start,deposit_peak_end,payment_deadline_minutes,refund_policy,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(branch_id) DO UPDATE SET reservations_enabled=excluded.reservations_enabled,auto_confirm=excluded.auto_confirm,reservation_duration=excluded.reservation_duration,max_party_size=excluded.max_party_size,customer_notice=excluded.customer_notice,buffer_minutes=excluded.buffer_minutes,slot_interval=excluded.slot_interval,sms_confirmation_enabled=excluded.sms_confirmation_enabled,sms_reminder_enabled=excluded.sms_reminder_enabled,sms_reminder_minutes=excluded.sms_reminder_minutes,deposit_enabled=excluded.deposit_enabled,deposit_mode=excluded.deposit_mode,deposit_amount_rials=excluded.deposit_amount_rials,deposit_peak_only=excluded.deposit_peak_only,deposit_peak_start=excluded.deposit_peak_start,deposit_peak_end=excluded.deposit_peak_end,payment_deadline_minutes=excluded.payment_deadline_minutes,refund_policy=excluded.refund_policy,updated_at=excluded.updated_at").bind(branchId,s.reservationsEnabled?1:0,s.autoConfirm?1:0,s.reservationDuration,s.maxPartySize,s.customerNotice,s.bufferMinutes,s.slotInterval,s.smsConfirmationEnabled?1:0,s.smsReminderEnabled?1:0,s.smsReminderMinutes,s.depositEnabled?1:0,s.depositMode,s.depositAmountRials,s.depositPeakOnly?1:0,s.depositPeakStart,s.depositPeakEnd,s.paymentDeadlineMinutes,s.refundPolicy,now)]);return s}
async function readSchedule(db,branch){const [hoursResult,closuresResult]=await db.batch([db.prepare("SELECT weekday,open_time,close_time,closed FROM operating_hours WHERE branch_id=? ORDER BY weekday").bind(branch.id),db.prepare("SELECT id,start_date,end_date,reason FROM closures WHERE branch_id=? ORDER BY start_date DESC LIMIT 50").bind(branch.id)]),rows=hoursResult.results||[],byDay=new Map(rows.map(r=>[r.weekday,{weekday:r.weekday,openTime:r.open_time,closeTime:r.close_time,closed:Boolean(r.closed)}]));return {hours:defaultHours().map(h=>byDay.get(h.weekday)||h),closures:(closuresResult.results||[]).map(r=>({id:r.id,startDate:r.start_date,endDate:r.end_date,reason:r.reason}))}}
async function writeSchedule(db,branch,body){const hours=Array.isArray(body.hours)?body.hours:[],closures=Array.isArray(body.closures)?body.closures:[],now=new Date().toISOString(),statements=[db.prepare("DELETE FROM operating_hours WHERE branch_id=?").bind(branch.id),db.prepare("DELETE FROM closures WHERE branch_id=?").bind(branch.id)];for(let weekday=0;weekday<7;weekday++){const item=hours.find(x=>Number(x.weekday)===weekday)||defaultHours()[weekday],open=validTime(item.openTime)?item.openTime:"10:00",close=validTime(item.closeTime)?item.closeTime:"23:00";statements.push(db.prepare("INSERT INTO operating_hours (branch_id,weekday,open_time,close_time,closed) VALUES (?,?,?,?,?)").bind(branch.id,weekday,open,close,item.closed?1:0))}for(const item of closures.slice(0,50)){if(!validDate(item.startDate)||!validDate(item.endDate)||item.endDate<item.startDate)continue;statements.push(db.prepare("INSERT INTO closures (id,branch_id,start_date,end_date,reason,created_at) VALUES (?,?,?,?,?,?)").bind(item.id||randomId("closure"),branch.id,item.startDate,item.endDate,String(item.reason||"").slice(0,100),now))}await db.batch(statements);return readSchedule(db,branch)}
async function dayRules(db,branch,date){const weekday=new Date(`${date}T12:00:00Z`).getUTCDay(),[hours,closure]=await db.batch([db.prepare("SELECT open_time,close_time,closed FROM operating_hours WHERE branch_id=? AND weekday=? LIMIT 1").bind(branch.id,weekday),db.prepare("SELECT reason FROM closures WHERE branch_id=? AND start_date<=? AND end_date>=? ORDER BY start_date DESC LIMIT 1").bind(branch.id,date,date)]),h=hours.results?.[0]||defaultHours()[weekday],c=closure.results?.[0];return {openTime:h.open_time||h.openTime,closeTime:h.close_time||h.closeTime,closed:Boolean(h.closed)||Boolean(c),reason:c?.reason||(h.closed?"The café is closed on this date":"")}}
async function availableTables(db,date,time,settings,tables){const locks=lockTimes(date,time,settings.reservationDuration,settings.bufferMinutes,settings.slotInterval),placeholders=locks.map(()=>"?").join(","),result=await db.prepare(`SELECT DISTINCT table_id FROM reservation_locks WHERE lock_start IN (${placeholders})`).bind(...locks).all(),busy=new Set((result.results||[]).map(r=>r.table_id));return tables.filter(t=>!busy.has(t.id))}
async function availability(db,branch,date,partySize,settings){const rules=await dayRules(db,branch,date);if(rules.closed)return {date,closed:true,reason:rules.reason,slots:[]};const mode=["indoor","outdoor","both"].includes(branch.space_mode)?branch.space_mode:"indoor",result=await db.prepare("SELECT t.id,t.name,t.capacity FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? AND t.reservable=1 AND (?='both' OR a.kind=?) ORDER BY t.name").bind(branch.id,mode,mode).all(),tables=result.results||[],start=minutes(rules.openTime),latest=minutes(rules.closeTime)-settings.reservationDuration,slots=[];for(let value=start;value<=latest;value+=settings.slotInterval){const time=`${pad(Math.floor(value/60))}:${pad(value%60)}`,free=await availableTables(db,date,time,settings,tables),eligible=free.filter(t=>t.capacity>=partySize);slots.push({time,available:eligible.length>0,tableIds:eligible.map(t=>t.id),remaining:eligible.length})}return {date,closed:false,reason:"",openTime:rules.openTime,closeTime:rules.closeTime,slots}}
function depositFor(settings,time,partySize){if(!settings.depositEnabled)return 0;if(settings.depositPeakOnly&&(minutes(time)<minutes(settings.depositPeakStart)||minutes(time)>=minutes(settings.depositPeakEnd)))return 0;return settings.depositMode==="per_person"?settings.depositAmountRials*partySize:settings.depositAmountRials}
async function expireUnpaidReservations(db,branchId=null){const condition=branchId?" AND branch_id=?":"",query=`SELECT id FROM reservations WHERE payment_status='pending' AND status='pending' AND payment_due_at<=?${condition} LIMIT 50`,statement=db.prepare(query),result=branchId?await statement.bind(new Date().toISOString(),branchId).all():await statement.bind(new Date().toISOString()).all(),ids=(result.results||[]).map(row=>row.id);if(!ids.length)return {expired:0};const now=new Date().toISOString(),statements=[];for(const id of ids){statements.push(db.prepare("UPDATE reservations SET status='cancelled',payment_status='failed',updated_at=? WHERE id=? AND payment_status='pending'").bind(now,id));statements.push(db.prepare("DELETE FROM reservation_locks WHERE reservation_id=?").bind(id));statements.push(db.prepare("UPDATE sms_messages SET status='cancelled' WHERE reservation_id=? AND status='queued'").bind(id))}await db.batch(statements);return {expired:ids.length}}

async function createReservation(env,branch,body,settings,operational=false){
  const db=env.DB;
  const rawMobile=normalizeMobile(body.mobile),mobile=rawMobile||"",name=String(body.customerName||"").trim().slice(0,70),date=body.date,time=body.time,partySize=Number(body.partySize),ids=[...new Set(Array.isArray(body.tableIds)?body.tableIds.map(String):[])],source=["phone","walk_in"].includes(body.source)?body.source:"web";
  if(!operational&&!settings.reservationsEnabled)return reply({error:"reservations_disabled",message:"Online booking is temporarily paused."},409);
  if(!name)return reply({error:"name_required",message:"Enter a guest name."},400);
  if(!operational&&!rawMobile)return reply({error:"invalid_mobile",message:"Enter a valid mobile number."},400);
  if(body.mobile&&!rawMobile)return reply({error:"invalid_mobile",message:"Enter a valid mobile number."},400);
  if(!validDate(date)||!validTime(time))return reply({error:"invalid_datetime",message:"Invalid date or time."},400);
  if(!Number.isInteger(partySize)||partySize<1||partySize>settings.maxPartySize)return reply({error:"invalid_party_size",message:"Invalid party size."},400);
  if(!ids.length||ids.length>4)return reply({error:"table_required",message:"Choose a table."},400);
  const rules=await dayRules(db,branch,date),start=minutes(time);if(rules.closed||start<minutes(rules.openTime)||start+settings.reservationDuration>minutes(rules.closeTime))return reply({error:"outside_hours",message:rules.reason||"This time is outside café hours."},409);
  const placeholders=ids.map(()=>"?").join(","),tableResult=await db.prepare(`SELECT t.id,t.name,t.capacity FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? AND t.reservable=1 AND t.id IN (${placeholders})`).bind(branch.id,...ids).all(),tables=tableResult.results||[];
  if(tables.length!==ids.length)return reply({error:"invalid_table",message:"Invalid table."},400);if(tables.reduce((sum,t)=>sum+t.capacity,0)<partySize)return reply({error:"insufficient_capacity",message:"The table is too small for the party."},400);
  const now=new Date().toISOString(),reservationId=randomId("reservation"),customerId=mobile?`customer:${branch.cafe_id}:${mobile}`:null,code=trackingCode(),depositAmount=operational?0:depositFor(settings,time,partySize),paymentStatus=depositAmount>0?"pending":"not_required",paymentDueAt=depositAmount>0?new Date(Date.now()+settings.paymentDeadlineMinutes*60000).toISOString():null,status=depositAmount>0?"pending":(operational?(body.status==="pending"?"pending":"confirmed"):(settings.autoConfirm?"confirmed":"pending")),reservedAt=`${date}T${time}`,locks=lockTimes(date,time,settings.reservationDuration,settings.bufferMinutes,settings.slotInterval),statements=[];
  if(customerId)statements.push(db.prepare("INSERT INTO customers (id,cafe_id,mobile,name,last_seen_at,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(cafe_id,mobile) DO UPDATE SET name=excluded.name,last_seen_at=excluded.last_seen_at").bind(customerId,branch.cafe_id,mobile,name,now,now));
  statements.push(db.prepare("INSERT INTO reservations (id,branch_id,customer_id,tracking_code,customer_name,mobile,party_size,reserved_at,duration_minutes,buffer_minutes,status,source,notes,internal_notes,deposit_amount_rials,payment_status,payment_due_at,paid_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(reservationId,branch.id,customerId,code,name,mobile,partySize,reservedAt,settings.reservationDuration,settings.bufferMinutes,status,source,String(body.notes||"").trim().slice(0,240),String(body.internalNotes||"").trim().slice(0,500),depositAmount,paymentStatus,paymentDueAt,null,now,now));
  for(const t of tables)statements.push(db.prepare("INSERT INTO reservation_tables (reservation_id,table_id) VALUES (?,?)").bind(reservationId,t.id));for(const t of tables)for(const lock of locks)statements.push(db.prepare("INSERT INTO reservation_locks (id,reservation_id,table_id,lock_start) VALUES (?,?,?,?)").bind(`${t.id}:${lock}`,reservationId,t.id,lock));
  try{await db.batch(statements)}catch(error){console.error("reservation_conflict",error);return reply({error:"slot_taken",message:"This table was just booked. Choose another table or time."},409)}
  const reservation={id:reservationId,trackingCode:code,customerName:name,mobile,partySize,date,time,durationMinutes:settings.reservationDuration,tables:tables.map(t=>t.name),source};let notifications={confirmation:"skipped",reminder:"skipped"};if(!depositAmount)try{notifications=await queueReservationMessages(env,branch,reservation,settings)}catch(error){console.error("reservation_notification_queue_failed",error);notifications={confirmation:"failed",reminder:"failed"}}return reply({trackingCode:code,status,reservation,notifications,payment:{required:depositAmount>0,amountRials:depositAmount,status:paymentStatus,dueAt:paymentDueAt,refundPolicy:settings.refundPolicy,provider:"demo"}},201)
}
async function lookupReservation(db,code,mobile){const normalized=normalizeMobile(mobile);if(!normalized)return null;return db.prepare("SELECT r.id,r.branch_id,r.tracking_code,r.customer_name,r.mobile,r.party_size,r.reserved_at,r.duration_minutes,r.status,r.notes,r.deposit_amount_rials,r.payment_status,r.payment_due_at,r.paid_at,b.name AS branch_name,s.refund_policy,GROUP_CONCAT(t.name,', ') AS table_names FROM reservations r JOIN branches b ON b.id=r.branch_id LEFT JOIN branch_settings s ON s.branch_id=b.id LEFT JOIN reservation_tables rt ON rt.reservation_id=r.id LEFT JOIN cafe_tables t ON t.id=rt.table_id WHERE r.tracking_code=? AND r.mobile=? GROUP BY r.id LIMIT 1").bind(code,normalized).first()}
function publicReservation(row){return {trackingCode:row.tracking_code,customerName:row.customer_name,mobile:row.mobile,partySize:row.party_size,date:row.reserved_at.slice(0,10),time:row.reserved_at.slice(11,16),durationMinutes:row.duration_minutes,status:row.status,branchName:row.branch_name,tables:row.table_names?row.table_names.split(", "):[],notes:row.notes,payment:{required:Number(row.deposit_amount_rials)>0,amountRials:Number(row.deposit_amount_rials||0),status:row.payment_status||"not_required",dueAt:row.payment_due_at,paidAt:row.paid_at,refundPolicy:row.refund_policy||defaultSettings.refundPolicy,provider:"demo"}}}

function tehranNow(){const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`,key:`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`}}
function operationalReservation(row){return {id:row.id,trackingCode:row.tracking_code,customerName:row.customer_name,mobile:row.mobile,partySize:row.party_size,date:row.reserved_at.slice(0,10),time:row.reserved_at.slice(11,16),durationMinutes:row.duration_minutes,status:row.status,source:row.source,notes:row.notes,internalNotes:row.internal_notes||"",tableIds:row.table_ids?row.table_ids.split("|"):[],tables:row.table_names?row.table_names.split(", "):[],createdAt:row.created_at}}
async function readOperations(db,branch,date,session,viewTime,settings){
  const spaceMode=["indoor","outdoor","both"].includes(branch.space_mode)?branch.space_mode:"indoor";
  const [reservationsResult,tablesResult,waitlistResult]=await db.batch([
    db.prepare("SELECT r.*,GROUP_CONCAT(t.id,'|') AS table_ids,GROUP_CONCAT(t.name,', ') AS table_names FROM reservations r LEFT JOIN reservation_tables rt ON rt.reservation_id=r.id LEFT JOIN cafe_tables t ON t.id=rt.table_id WHERE r.branch_id=? AND r.reserved_at>=? AND r.reserved_at<? GROUP BY r.id ORDER BY r.reserved_at").bind(branch.id,`${date}T00:00`,`${date}T23:59`),
    db.prepare("SELECT t.id,t.name,t.capacity,t.shape,t.position_x,t.position_y,t.reservable,t.operational_status,a.id AS area_id,a.name AS area_name FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? AND (?='both' OR a.kind=?) ORDER BY a.sort_order,t.name").bind(branch.id,spaceMode,spaceMode),
    db.prepare("SELECT id,customer_name,mobile,party_size,quoted_minutes,status,notes,created_at,updated_at FROM waitlist_entries WHERE branch_id=? AND status IN ('waiting','called') ORDER BY created_at").bind(branch.id)
  ]);
  const reservations=(reservationsResult.results||[]).map(operationalReservation),now=tehranNow(),selectedTime=validTime(viewTime)?viewTime:(date===now.date?now.time:"12:00"),viewKey=`${date}T${selectedTime}`,viewMinute=minutes(selectedTime),tableRows=tablesResult.results||[],rules=await dayRules(db,branch,date),withinHours=!rules.closed&&viewMinute>=minutes(rules.openTime)&&viewMinute+settings.reservationDuration<=minutes(rules.closeTime),freeIds=new Set(withinHours?(await availableTables(db,date,selectedTime,settings,tableRows)).map(t=>t.id):[]);
  const tables=tableRows.map(table=>{let liveStatus=table.operational_status||"available",reservation=null;const canQuickLock=Boolean(table.reservable&&liveStatus==="available"&&freeIds.has(table.id));if(!["dirty","inactive"].includes(liveStatus)){const active=reservations.filter(r=>r.tableIds.includes(table.id)&&!["cancelled","completed","no_show"].includes(r.status)),match=active.find(r=>{const start=minutes(r.time);return viewMinute>=start&&viewMinute<start+r.durationMinutes}),future=active.filter(r=>minutes(r.time)>viewMinute).sort((a,b)=>a.time.localeCompare(b.time))[0];if(match){reservation=match;liveStatus="occupied"}else if(future){reservation=future;liveStatus=canQuickLock?"available":"upcoming"}else liveStatus="available"}return {id:table.id,name:table.name,capacity:table.capacity,shape:table.shape,x:table.position_x,y:table.position_y,reservable:Boolean(table.reservable),manualStatus:table.operational_status||"available",liveStatus,canQuickLock,areaId:table.area_id,areaName:table.area_name,reservation:reservation?{trackingCode:reservation.trackingCode,customerName:reservation.customerName,time:reservation.time,partySize:reservation.partySize,source:reservation.source}:null}});
  const active=reservations.filter(r=>!["cancelled","completed","no_show"].includes(r.status)),occupied=tables.filter(t=>t.liveStatus==="occupied"),totalCapacity=tables.filter(t=>t.reservable&&t.manualStatus!=="inactive").reduce((s,t)=>s+t.capacity,0),usedCapacity=occupied.reduce((s,t)=>s+t.capacity,0),next=active.filter(r=>`${r.date}T${r.time}`>=viewKey).sort((a,b)=>a.time.localeCompare(b.time))[0]||null,delayed=active.filter(r=>["pending","confirmed"].includes(r.status)&&`${r.date}T${r.time}`<viewKey).length;
  const canReadReservations=hasPermission(session,"reservations.read"),canReadWaitlist=hasPermission(session,"waitlist.read"),visibleTables=canReadReservations?tables:tables.map(table=>({...table,reservation:table.reservation?{time:table.reservation.time}:null}));
  return {date,viewTime:selectedTime,branch:{id:branch.id,name:branch.name},permissions:permissionsFor(session.role),stats:{reservations:canReadReservations?active.length:0,guests:canReadReservations?active.reduce((s,r)=>s+r.partySize,0):0,occupiedTables:occupied.length,totalTables:tables.length,capacityPercent:totalCapacity?Math.round(usedCapacity/totalCapacity*100):0,remainingCapacity:Math.max(0,totalCapacity-usedCapacity),waiting:canReadWaitlist?(waitlistResult.results||[]).filter(x=>x.status==="waiting").length:0,delayed:canReadReservations?delayed:0},nextReservation:canReadReservations?next:null,reservations:canReadReservations?reservations:[],tables:visibleTables,waitlist:canReadWaitlist?(waitlistResult.results||[]).map(x=>({id:x.id,customerName:x.customer_name,mobile:x.mobile,partySize:x.party_size,quotedMinutes:x.quoted_minutes,status:x.status,notes:x.notes,createdAt:x.created_at})):[]}
}
async function updateOperationalReservation(db,branch,code,body,settings){
  const row=await db.prepare("SELECT * FROM reservations WHERE branch_id=? AND tracking_code=? LIMIT 1").bind(branch.id,code).first();if(!row)return reply({error:"reservation_not_found",message:"Booking not found."},404);
  const name=String(body.customerName??row.customer_name).trim().slice(0,70),mobile=body.mobile===undefined?row.mobile:(normalizeMobile(body.mobile)||""),partySize=Number(body.partySize??row.party_size),date=body.date||row.reserved_at.slice(0,10),time=body.time||row.reserved_at.slice(11,16),status=body.status||row.status,allowed=["pending","confirmed","arrived","completed","cancelled","no_show"];
  if(!name||!validDate(date)||!validTime(time)||!Number.isInteger(partySize)||partySize<1||partySize>settings.maxPartySize||!allowed.includes(status))return reply({error:"invalid_reservation",message:"Invalid booking details."},400);
  let tableIds=Array.isArray(body.tableIds)?[...new Set(body.tableIds.map(String))]:[];if(!tableIds.length){const current=await db.prepare("SELECT table_id FROM reservation_tables WHERE reservation_id=?").bind(row.id).all();tableIds=(current.results||[]).map(x=>x.table_id)}
  const marks=tableIds.map(()=>"?").join(","),tableResult=await db.prepare(`SELECT t.id,t.name,t.capacity FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=? AND t.reservable=1 AND t.id IN (${marks})`).bind(branch.id,...tableIds).all(),tables=tableResult.results||[];if(tables.length!==tableIds.length||tables.reduce((s,t)=>s+t.capacity,0)<partySize)return reply({error:"invalid_table",message:"Invalid table or capacity."},400);
  const now=new Date().toISOString(),internalNotes=body.internalNotes??row.internal_notes??"",statements=[db.prepare("DELETE FROM reservation_locks WHERE reservation_id=?").bind(row.id),db.prepare("DELETE FROM reservation_tables WHERE reservation_id=?").bind(row.id),db.prepare("UPDATE reservations SET customer_name=?,mobile=?,party_size=?,reserved_at=?,status=?,notes=?,internal_notes=?,updated_at=? WHERE id=?").bind(name,mobile,partySize,`${date}T${time}`,status,String(body.notes??row.notes).slice(0,240),String(internalNotes).slice(0,500),now,row.id)];
  if(["cancelled","completed","no_show"].includes(status))statements.push(db.prepare("UPDATE sms_messages SET status='cancelled' WHERE reservation_id=? AND kind='reminder' AND status='queued'").bind(row.id));else statements.push(db.prepare("UPDATE sms_messages SET scheduled_at=?,mobile=?,customer_name=? WHERE reservation_id=? AND kind='reminder' AND status='queued'").bind(subtractLocalMinutes(`${date}T${time}`,settings.smsReminderMinutes),mobile,name,row.id));
  for(const table of tables)statements.push(db.prepare("INSERT INTO reservation_tables (reservation_id,table_id) VALUES (?,?)").bind(row.id,table.id));if(!["cancelled","completed","no_show"].includes(status)){for(const table of tables)for(const lock of lockTimes(date,time,row.duration_minutes,row.buffer_minutes,settings.slotInterval))statements.push(db.prepare("INSERT INTO reservation_locks (id,reservation_id,table_id,lock_start) VALUES (?,?,?,?)").bind(`${table.id}:${lock}`,row.id,table.id,lock))}
  try{await db.batch(statements)}catch(error){console.error("reservation_update_conflict",error);return reply({error:"slot_taken",message:"This table is booked at the selected time."},409)}if(status==="completed"&&row.status!=="completed")try{await awardLoyaltyVisit(db,branch,row,now)}catch(error){console.error("loyalty_award_failed",error)}return reply({trackingCode:code,status})
}
async function createWaitlist(db,branch,body){const name=String(body.customerName||"").trim().slice(0,70),mobile=body.mobile?normalizeMobile(body.mobile):"",partySize=Number(body.partySize),quoted=Math.max(0,Math.min(180,Number(body.quotedMinutes)||20));if(!name||!Number.isInteger(partySize)||partySize<1||partySize>30||body.mobile&&!mobile)return reply({error:"invalid_waitlist",message:"Invalid waitlist details."},400);const now=new Date().toISOString(),id=randomId("wait");await db.prepare("INSERT INTO waitlist_entries (id,branch_id,customer_name,mobile,party_size,quoted_minutes,status,notes,created_at,updated_at) VALUES (?,?,?,?,? ,?,'waiting',?,?,?)").bind(id,branch.id,name,mobile,partySize,quoted,String(body.notes||"").slice(0,240),now,now).run();return reply({id,status:"waiting"},201)}
async function updateWaitlist(db,branch,id,body){const allowed=["waiting","called","seated","cancelled"],status=body.status;if(!allowed.includes(status))return reply({error:"invalid_status"},400);const result=await db.prepare("UPDATE waitlist_entries SET status=?,updated_at=? WHERE id=? AND branch_id=?").bind(status,new Date().toISOString(),id,branch.id).run();return result.meta?.changes?reply({id,status}):reply({error:"waitlist_not_found"},404)}

async function awardLoyaltyVisit(db,branch,reservation,now){if(!reservation.customer_id)return;const existing=await db.prepare("SELECT id FROM loyalty_transactions WHERE reservation_id=? LIMIT 1").bind(reservation.id).first();if(existing)return;await db.batch([db.prepare("INSERT INTO loyalty_transactions (id,cafe_id,customer_id,branch_id,reservation_id,type,points,note,created_at) VALUES (?,?,?,?,?,'visit',10,'points for a completed visit',?)").bind(randomId("loyalty"),branch.cafe_id,reservation.customer_id,branch.id,reservation.id,now),db.prepare("UPDATE customers SET points=points+10,completed_visits=completed_visits+1,last_seen_at=? WHERE id=? AND cafe_id=?").bind(now,reservation.customer_id,branch.cafe_id)])}

async function readReports(db,session,url){
  if(!hasPermission(session,"reports.read"))return reply({error:"forbidden",message:"You cannot access reports."},403);
  const days=[7,30,90].includes(Number(url.searchParams.get("days")))?Number(url.searchParams.get("days")):30,start=new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10),requestedBranch=String(url.searchParams.get("branch")||""),branchId=session.role==="owner"?requestedBranch:(session.branch_id||"");
  if(branchId){const allowed=await db.prepare("SELECT id FROM branches WHERE id=? AND cafe_id=? LIMIT 1").bind(branchId,session.cafe_id).first();if(!allowed)return reply({error:"invalid_branch"},400)}
  const suffix=branchId?" AND b.id=?":"",bindValues=branchId?[session.cafe_id,`${start}T00:00`,branchId]:[session.cafe_id,`${start}T00:00`];
  const [summaryResult,dailyResult,hoursResult,branchesResult,repeatResult]=await db.batch([
    db.prepare(`SELECT COUNT(*) AS reservations,COALESCE(SUM(r.party_size),0) AS guests,SUM(CASE WHEN r.status='completed' THEN 1 ELSE 0 END) AS completed,SUM(CASE WHEN r.status='no_show' THEN 1 ELSE 0 END) AS no_show,COUNT(DISTINCT NULLIF(r.mobile,'')) AS unique_customers FROM reservations r JOIN branches b ON b.id=r.branch_id WHERE b.cafe_id=? AND r.reserved_at>=?${suffix}`).bind(...bindValues),
    db.prepare(`SELECT SUBSTR(r.reserved_at,1,10) AS day,COUNT(*) AS reservations,COALESCE(SUM(r.party_size),0) AS guests FROM reservations r JOIN branches b ON b.id=r.branch_id WHERE b.cafe_id=? AND r.reserved_at>=?${suffix} GROUP BY day ORDER BY day`).bind(...bindValues),
    db.prepare(`SELECT SUBSTR(r.reserved_at,12,2) AS hour,COUNT(*) AS reservations FROM reservations r JOIN branches b ON b.id=r.branch_id WHERE b.cafe_id=? AND r.reserved_at>=?${suffix} GROUP BY hour ORDER BY reservations DESC,hour LIMIT 6`).bind(...bindValues),
    db.prepare("SELECT b.id,b.name,COUNT(r.id) AS reservations,COALESCE(SUM(r.party_size),0) AS guests,SUM(CASE WHEN r.status='completed' THEN 1 ELSE 0 END) AS completed FROM branches b LEFT JOIN reservations r ON r.branch_id=b.id AND r.reserved_at>=? WHERE b.cafe_id=? AND b.active=1 GROUP BY b.id ORDER BY reservations DESC").bind(`${start}T00:00`,session.cafe_id),
    db.prepare(`SELECT COUNT(*) AS count FROM (SELECT r.mobile FROM reservations r JOIN branches b ON b.id=r.branch_id WHERE b.cafe_id=? AND r.reserved_at>=? AND r.mobile!=''${suffix} GROUP BY r.mobile HAVING COUNT(*)>1)`).bind(...bindValues)
  ]);
  const row=summaryResult.results?.[0]||{},reservations=Number(row.reservations||0),completed=Number(row.completed||0),noShow=Number(row.no_show||0);
  return reply({days,start,branchId:branchId||null,summary:{reservations,guests:Number(row.guests||0),completed,noShow,uniqueCustomers:Number(row.unique_customers||0),repeatCustomers:Number(repeatResult.results?.[0]?.count||0),completionRate:reservations?Math.round(completed/reservations*100):0,noShowRate:reservations?Math.round(noShow/reservations*100):0},daily:(dailyResult.results||[]).map(item=>({date:item.day,reservations:Number(item.reservations),guests:Number(item.guests)})),busyHours:(hoursResult.results||[]).map(item=>({hour:`${item.hour}:00`,reservations:Number(item.reservations)})),branches:(branchesResult.results||[]).filter(item=>!branchId||item.id===branchId).map(item=>({id:item.id,name:item.name,reservations:Number(item.reservations),guests:Number(item.guests),completed:Number(item.completed||0)}))})
}

async function readLoyalty(db,session,url){
  if(!hasPermission(session,"loyalty.read"))return reply({error:"forbidden",message:"You cannot access loyalty."},403);
  const query=String(url.searchParams.get("q")||"").trim().slice(0,60),escapedQuery=query.replace(/[\\%_]/g,"\\$&"),pattern=`%${escapedQuery}%`,branchScope=session.role==="owner"?"":" AND EXISTS (SELECT 1 FROM reservations r WHERE r.customer_id=c.id AND r.branch_id=?)",listParams=session.role==="owner"?[session.cafe_id,query,pattern,pattern]:[session.cafe_id,session.branch_id,query,pattern,pattern],result=await db.prepare(`SELECT c.id,c.name,c.mobile,c.points,c.completed_visits,c.last_seen_at,c.created_at FROM customers c WHERE c.cafe_id=?${branchScope} AND (?='' OR c.name LIKE ? ESCAPE '\\' OR c.mobile LIKE ? ESCAPE '\\') ORDER BY c.points DESC,c.last_seen_at DESC LIMIT 100`).bind(...listParams).all(),customers=(result.results||[]).map(row=>({id:row.id,name:row.name,mobile:row.mobile,points:Number(row.points||0),completedVisits:Number(row.completed_visits||0),lastSeenAt:row.last_seen_at,createdAt:row.created_at}));
  const statsParams=session.role==="owner"?[session.cafe_id]:[session.cafe_id,session.branch_id],stats=await db.prepare(`SELECT COUNT(*) AS total,COALESCE(SUM(CASE WHEN c.completed_visits>1 THEN 1 ELSE 0 END),0) AS returning_customers,COALESCE(SUM(c.points),0) AS points FROM customers c WHERE c.cafe_id=?${branchScope}`).bind(...statsParams).first();return reply({pointsPerVisit:10,rewardThreshold:100,canWrite:hasPermission(session,"loyalty.write"),stats:{total:Number(stats?.total||0),returning:Number(stats?.returning_customers||0),points:Number(stats?.points||0)},customers})
}

async function adjustLoyalty(db,session,customerId,body){
  if(!hasPermission(session,"loyalty.write"))return reply({error:"forbidden",message:"You cannot adjust guest points."},403);if(!customerId||customerId.length>180)return reply({error:"invalid_customer",message:"Invalid guest ID."},400);const points=Number(body.points),note=String(body.note||"").trim().slice(0,120);if(!Number.isInteger(points)||points===0||points<-500||points>500)return reply({error:"invalid_points",message:"Points must be between -500 and 500."},400);const customer=session.role==="owner"?await db.prepare("SELECT id,points FROM customers WHERE id=? AND cafe_id=? LIMIT 1").bind(customerId,session.cafe_id).first():await db.prepare("SELECT c.id,c.points FROM customers c WHERE c.id=? AND c.cafe_id=? AND EXISTS (SELECT 1 FROM reservations r WHERE r.customer_id=c.id AND r.branch_id=?) LIMIT 1").bind(customerId,session.cafe_id,session.branch_id).first();if(!customer)return reply({error:"customer_not_found",message:"Guest not found or branch access denied."},404);const now=new Date().toISOString(),results=await db.batch([db.prepare("UPDATE customers SET points=points+? WHERE id=? AND cafe_id=? AND points+?>=0").bind(points,customerId,session.cafe_id,points),db.prepare("INSERT INTO loyalty_transactions (id,cafe_id,customer_id,branch_id,reservation_id,type,points,note,created_at) SELECT ?,?,?,?,NULL,?,?,?,? WHERE changes()>0").bind(randomId("loyalty"),session.cafe_id,customerId,session.branch_id||null,points>0?"bonus":"redeem",points,note||(points>0?"bonus points":"Reward redemption"),now)]);if(!results?.[0]?.meta?.changes)return reply({error:"insufficient_points",message:"Guest has insufficient points."},409);return readLoyalty(db,session,new URL("https://local/api/loyalty"))
}

async function readNotifications(env,cafeSlug,branchSlug){const branch=await branchRow(env.DB,cafeSlug,branchSlug),settings=await readSettings(env.DB,cafeSlug,branchSlug),result=await env.DB.prepare("SELECT id,kind,mobile,customer_name,message,status,scheduled_at,sent_at,provider,error,created_at FROM sms_messages WHERE branch_id=? ORDER BY created_at DESC LIMIT 40").bind(branch.id).all(),messages=(result.results||[]).map(row=>({id:row.id,kind:row.kind,mobile:maskMobile(row.mobile),customerName:row.customer_name,message:row.message,status:row.status,scheduledAt:row.scheduled_at,sentAt:row.sent_at,provider:row.provider,error:row.error,createdAt:row.created_at}));return {mode:env.KAVENEGAR_API_KEY&&env.KAVENEGAR_CONFIRMATION_TEMPLATE&&env.KAVENEGAR_REMINDER_TEMPLATE?"kavenegar":"demo",settings:{confirmationEnabled:settings.smsConfirmationEnabled,reminderEnabled:settings.smsReminderEnabled,reminderMinutes:settings.smsReminderMinutes},stats:{total:messages.length,sent:messages.filter(item=>["sent","demo_sent"].includes(item.status)).length,queued:messages.filter(item=>item.status==="queued").length,failed:messages.filter(item=>item.status==="failed").length},messages}}
async function writeNotificationSettings(env,cafeSlug,branchSlug,body){const branch=await branchRow(env.DB,cafeSlug,branchSlug);if(!branch)return reply({error:"branch_not_found"},404);const reminderMinutes=[60,120,180,360,1440].includes(Number(body.reminderMinutes))?Number(body.reminderMinutes):120;await env.DB.prepare("UPDATE branch_settings SET sms_confirmation_enabled=?,sms_reminder_enabled=?,sms_reminder_minutes=?,updated_at=? WHERE branch_id=?").bind(body.confirmationEnabled===false?0:1,body.reminderEnabled===false?0:1,reminderMinutes,new Date().toISOString(),branch.id).run();return reply(await readNotifications(env,cafeSlug,branchSlug))}
async function payReservationDemo(env,row){if(row.payment_status==="paid")return reply(publicReservation(row));if(row.payment_status!=="pending"||!Number(row.deposit_amount_rials))return reply({error:"payment_not_available",message:"This booking requires no payment."},409);if(row.payment_due_at&&row.payment_due_at<=new Date().toISOString()){await expireUnpaidReservations(env.DB,row.branch_id);return reply({error:"payment_expired",message:"Payment expired and the table is available again."},409)}const now=new Date().toISOString(),reference=`DEMO-${Date.now()}`;await env.DB.batch([env.DB.prepare("UPDATE reservations SET payment_status='paid',paid_at=?,status='confirmed',updated_at=? WHERE id=? AND payment_status='pending'").bind(now,now,row.id),env.DB.prepare("INSERT INTO payment_transactions (id,reservation_id,branch_id,type,amount_rials,status,provider,reference,created_at) VALUES (?,?,?,'payment',?,'success','demo',?,?)").bind(randomId("payment"),row.id,row.branch_id,Number(row.deposit_amount_rials),reference,now)]);const updated=await lookupReservation(env.DB,row.tracking_code,row.mobile);return reply({...publicReservation(updated),reference})}
async function readPayments(db,session,url){if(!hasPermission(session,"payments.read"))return reply({error:"forbidden",message:"You cannot access payments."},403);const branchId=String(url.searchParams.get("branch")||session.branch_id||""),scope=session.role==="owner"?(branchId?" AND p.branch_id=?":""):" AND p.branch_id=?",params=session.role==="owner"?(branchId?[session.cafe_id,branchId]:[session.cafe_id]):[session.cafe_id,session.branch_id],result=await db.prepare(`SELECT p.id,p.reservation_id,p.type,p.amount_rials,p.status,p.provider,p.reference,p.created_at,r.tracking_code,r.customer_name,r.mobile,b.name AS branch_name FROM payment_transactions p JOIN reservations r ON r.id=p.reservation_id JOIN branches b ON b.id=p.branch_id WHERE b.cafe_id=?${scope} ORDER BY p.created_at DESC LIMIT 100`).bind(...params).all(),pending=await db.prepare(`SELECT COUNT(*) AS count,COALESCE(SUM(r.deposit_amount_rials),0) AS amount FROM reservations r JOIN branches b ON b.id=r.branch_id WHERE b.cafe_id=? AND r.payment_status='pending'${scope.replaceAll('p.branch_id','r.branch_id')}`).bind(...params).first(),transactions=(result.results||[]).map(row=>({id:row.id,reservationId:row.reservation_id,type:row.type,amountRials:Number(row.amount_rials),status:row.status,provider:row.provider,reference:row.reference,createdAt:row.created_at,trackingCode:row.tracking_code,customerName:row.customer_name,mobile:maskMobile(row.mobile),branchName:row.branch_name})),paid=transactions.filter(item=>item.type==="payment"&&item.status==="success").reduce((sum,item)=>sum+item.amountRials,0),refunded=transactions.filter(item=>item.type==="refund"&&item.status==="success").reduce((sum,item)=>sum+item.amountRials,0);return reply({mode:"demo",canWrite:hasPermission(session,"payments.write"),summary:{paid,refunded,pending:Number(pending?.amount||0),pendingCount:Number(pending?.count||0)},transactions})}
async function refundPayment(db,session,transactionId){if(!hasPermission(session,"payments.write"))return reply({error:"forbidden",message:"You cannot issue refunds."},403);const row=await db.prepare("SELECT p.*,b.cafe_id FROM payment_transactions p JOIN branches b ON b.id=p.branch_id WHERE p.id=? AND p.type='payment' AND p.status='success' LIMIT 1").bind(transactionId).first();if(!row||row.cafe_id!==session.cafe_id||(session.role!=="owner"&&row.branch_id!==session.branch_id))return reply({error:"payment_not_found"},404);const exists=await db.prepare("SELECT id FROM payment_transactions WHERE reservation_id=? AND type='refund' AND status='success' LIMIT 1").bind(row.reservation_id).first();if(exists)return reply({error:"already_refunded",message:"This deposit has already been refunded."},409);const now=new Date().toISOString(),reference=`REF-DEMO-${Date.now()}`;await db.batch([db.prepare("INSERT INTO payment_transactions (id,reservation_id,branch_id,type,amount_rials,status,provider,reference,created_at) VALUES (?,?,?,'refund',?,'success','demo',?,?)").bind(randomId("payment"),row.reservation_id,row.branch_id,row.amount_rials,reference,now),db.prepare("UPDATE reservations SET payment_status='refunded',status='cancelled',updated_at=? WHERE id=?").bind(now,row.reservation_id),db.prepare("DELETE FROM reservation_locks WHERE reservation_id=?").bind(row.reservation_id),db.prepare("UPDATE sms_messages SET status='cancelled' WHERE reservation_id=? AND status='queued'").bind(row.reservation_id)]);return reply({refunded:true,reference})}

async function handleBranchApi(request,env,url,cafeSlug,branchSlug,resource){if(!safeSlug(cafeSlug)||!safeSlug(branchSlug))return reply({error:"invalid_slug"},400);const branch=await branchRow(env.DB,cafeSlug,branchSlug);if(resource==="map"){if(request.method==="GET"){const map=await readMap(env.DB,cafeSlug,branchSlug);return map?reply(map):reply({error:"map_not_found"},404)}if(request.method==="PUT"){const length=Number(request.headers.get("content-length")||0);if(length>150000)return reply({error:"payload_too_large"},413);const result=await writeMap(env.DB,cafeSlug,branchSlug,await request.json());return result instanceof Response?result:reply(result)}}if(resource==="settings"){if(request.method==="GET")return reply(await readSettings(env.DB,cafeSlug,branchSlug));if(request.method==="PUT")return reply(await writeSettings(env.DB,cafeSlug,branchSlug,await request.json()))}if(!branch)return reply({error:"branch_not_found",message:"Publish the branch map first."},404);if(resource==="schedule"){if(request.method==="GET")return reply(await readSchedule(env.DB,branch));if(request.method==="PUT")return reply(await writeSchedule(env.DB,branch,await request.json()))}const settings=await readSettings(env.DB,cafeSlug,branchSlug);if(resource==="availability"&&request.method==="GET"){const date=url.searchParams.get("date"),partySize=Math.max(1,Math.min(settings.maxPartySize,Number(url.searchParams.get("party_size"))||2));if(!validDate(date))return reply({error:"invalid_date"},400);return reply(await availability(env.DB,branch,date,partySize,settings))}if(resource==="reservations"){if(request.method==="POST")return createReservation(env,branch,await request.json(),settings);if(request.method==="GET"){const date=url.searchParams.get("date");if(!validDate(date))return reply({error:"invalid_date"},400);const result=await env.DB.prepare("SELECT r.tracking_code,r.customer_name,r.mobile,r.party_size,r.reserved_at,r.status,GROUP_CONCAT(t.name,', ') AS table_names FROM reservations r LEFT JOIN reservation_tables rt ON rt.reservation_id=r.id LEFT JOIN cafe_tables t ON t.id=rt.table_id WHERE r.branch_id=? AND r.reserved_at>=? AND r.reserved_at<? GROUP BY r.id ORDER BY r.reserved_at").bind(branch.id,`${date}T00:00`,`${date}T23:59`).all();return reply({reservations:result.results||[]})}}return reply({error:"method_not_allowed"},405)}
async function handleApi(request,env,url){
  if(!env.DB)return reply({error:"database_unavailable"},503);
  try{
    if(url.pathname==="/api/auth/request"&&request.method==="POST")return requestOtp(env,await request.json());
    if(url.pathname==="/api/auth/verify"&&request.method==="POST")return verifyOtp(env,await request.json());
    if(url.pathname==="/api/auth/session"&&request.method==="GET"){const session=await sessionStaff(env.DB,request);return reply(session?{authenticated:true,staff:staffSessionPublic(session)}:{authenticated:false})}
    if(url.pathname==="/api/auth/logout"&&request.method==="POST"){const session=await sessionStaff(env.DB,request);if(session)await env.DB.prepare("DELETE FROM staff_sessions WHERE id=?").bind(session.session_id).run();return replyWithHeaders({authenticated:false},200,{"set-cookie":"mizo_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"})}
    if(url.pathname==="/api/reports"&&request.method==="GET"){const session=await sessionStaff(env.DB,request);if(!session)return reply({error:"authentication_required",message:"Sign in first."},401);return readReports(env.DB,session,url)}
    const paymentsMatch=url.pathname.match(/^\/api\/payments(?:\/([^/]+)\/refund)?$/);if(paymentsMatch){const session=await sessionStaff(env.DB,request);if(!session)return reply({error:"authentication_required",message:"Sign in first."},401);if(request.method==="GET"&&!paymentsMatch[1])return readPayments(env.DB,session,url);if(request.method==="POST"&&paymentsMatch[1])return refundPayment(env.DB,session,decodeURIComponent(paymentsMatch[1]));return reply({error:"method_not_allowed"},405)}
    const loyaltyMatch=url.pathname.match(/^\/api\/loyalty(?:\/([^/]+))?$/);if(loyaltyMatch){const session=await sessionStaff(env.DB,request);if(!session)return reply({error:"authentication_required",message:"Sign in first."},401);const customerId=loyaltyMatch[1]&&decodeURIComponent(loyaltyMatch[1]);if(request.method==="GET"&&!customerId)return readLoyalty(env.DB,session,url);if(request.method==="PATCH"&&customerId)return adjustLoyalty(env.DB,session,customerId,await request.json());return reply({error:"method_not_allowed"},405)}
    if(url.pathname==="/api/subscription"||url.pathname==="/api/subscription/renew"){const session=await sessionStaff(env.DB,request);if(!session)return reply({error:"authentication_required",message:"Sign in first."},401);if(request.method==="GET"&&url.pathname==="/api/subscription")return reply(await readSubscription(env.DB,session.cafe_id));if(request.method==="PUT"&&url.pathname==="/api/subscription")return updateSubscription(env.DB,session,await request.json());if(request.method==="POST"&&url.pathname.endsWith("/renew"))return renewSubscriptionDemo(env.DB,session);return reply({error:"method_not_allowed"},405)}
    if(url.pathname==="/api/saas/overview"){const admin=await requireSaasAdmin(env.DB,request);if(!admin)return reply({error:"forbidden",message:"SaaS admin access is not enabled for this account."},403);if(request.method==="GET")return reply(await readSaasOverview(env.DB));if(request.method==="PATCH")return updateSaasAccount(env.DB,await request.json());return reply({error:"method_not_allowed"},405)}
    const staffMatch=url.pathname.match(/^\/api\/staff(?:\/([^/]+))?$/);if(staffMatch){const session=await sessionStaff(env.DB,request);if(!session)return reply({error:"authentication_required",message:"Sign in first."},401);const id=staffMatch[1]&&decodeURIComponent(staffMatch[1]);if(request.method==="GET"&&!id)return listStaff(env.DB,session);if(request.method==="POST"&&!id)return saveStaff(env.DB,session,await request.json());if(request.method==="PATCH"&&id)return saveStaff(env.DB,session,await request.json(),id);return reply({error:"method_not_allowed"},405)}
    if(url.pathname==="/api/setup"){
      if(request.method==="GET")return reply(await readSetup(env.DB));
      if(request.method==="POST")return writeSetup(env.DB,await request.json());
      if(request.method==="PATCH"){const session=await sessionStaff(env.DB,request);if(!session||session.role!=="owner")return reply({error:"forbidden",message:"Only the café owner can access this section."},403);return writeSetup(env.DB,await request.json(),true)}
      return reply({error:"method_not_allowed"},405);
    }
    const branchesMatch=url.pathname.match(/^\/api\/branches(?:\/([^/]+))?$/);
    if(branchesMatch){const slug=branchesMatch[1]&&decodeURIComponent(branchesMatch[1]);if(request.method==="GET"&&!slug)return reply(await readSetup(env.DB));const session=await sessionStaff(env.DB,request);if(!session||session.role!=="owner")return reply({error:"forbidden",message:"Only the café owner can manage branches."},403);if(request.method==="POST"&&!slug)return createBranch(env.DB,await request.json());if(request.method==="PATCH"&&slug)return updateBranch(env.DB,slug,await request.json());return reply({error:"method_not_allowed"},405)}
    const notificationsMatch=url.pathname.match(/^\/api\/cafes\/([^/]+)\/branches\/([^/]+)\/notifications(?:\/(process))?$/);
    if(notificationsMatch){const [,cafeSlug,branchSlug,action]=notificationsMatch;if(!safeSlug(cafeSlug)||!safeSlug(branchSlug))return reply({error:"invalid_slug"},400);const branch=await branchRow(env.DB,cafeSlug,branchSlug),session=await sessionStaff(env.DB,request);if(!session||!branch||!canUseBranch(session,branch)||!hasPermission(session,"messages.read"))return reply({error:"forbidden",message:"You cannot access SMS for this branch."},403);if(request.method==="GET"&&!action)return reply(await readNotifications(env,cafeSlug,branchSlug));if(request.method==="PUT"&&!action){if(!hasPermission(session,"messages.write"))return reply({error:"forbidden",message:"You cannot change SMS settings."},403);return writeNotificationSettings(env,cafeSlug,branchSlug,await request.json())}if(request.method==="POST"&&action==="process"){if(!hasPermission(session,"messages.write"))return reply({error:"forbidden",message:"You cannot run reminders."},403);const result=await processDueReminders(env,branch.id);return reply({...result,notifications:await readNotifications(env,cafeSlug,branchSlug)})}return reply({error:"method_not_allowed"},405)}
    const opsMatch=url.pathname.match(/^\/api\/cafes\/([^/]+)\/branches\/([^/]+)\/operations(?:\/(reservations|waitlist|tables)(?:\/([^/]+))?)?$/);
    if(opsMatch){
      const [,cafeSlug,branchSlug,section,itemId]=opsMatch;if(!safeSlug(cafeSlug)||!safeSlug(branchSlug))return reply({error:"invalid_slug"},400);const branch=await branchRow(env.DB,cafeSlug,branchSlug);if(!branch)return reply({error:"branch_not_found"},404);const session=await sessionStaff(env.DB,request);if(!session||!canUseBranch(session,branch)||!hasPermission(session,"dashboard.view"))return reply({error:"forbidden",message:"You cannot access this branch's operations."},403);const settings=await readSettings(env.DB,cafeSlug,branchSlug);
      if(!section&&request.method==="GET"){const date=url.searchParams.get("date")||tehranNow().date,time=url.searchParams.get("time")||tehranNow().time;if(!validDate(date)||!validTime(time))return reply({error:"invalid_datetime"},400);return reply(await readOperations(env.DB,branch,date,session,time,settings))}
      if(section==="reservations"&&request.method==="POST"&&!itemId){if(!hasPermission(session,"reservations.write"))return reply({error:"forbidden",message:"You cannot create bookings."},403);return createReservation(env,branch,await request.json(),settings,true)}
      if(section==="reservations"&&request.method==="PATCH"&&itemId){if(!hasPermission(session,"reservations.write"))return reply({error:"forbidden",message:"You cannot edit bookings."},403);return updateOperationalReservation(env.DB,branch,itemId,await request.json(),settings)}
      if(section==="waitlist"&&request.method==="POST"&&!itemId){if(!hasPermission(session,"waitlist.write"))return reply({error:"forbidden",message:"You cannot manage the waitlist."},403);return createWaitlist(env.DB,branch,await request.json())}
      if(section==="waitlist"&&request.method==="PATCH"&&itemId){if(!hasPermission(session,"waitlist.write"))return reply({error:"forbidden",message:"You cannot manage the waitlist."},403);return updateWaitlist(env.DB,branch,itemId,await request.json())}
      if(section==="tables"&&request.method==="PATCH"&&itemId){if(!hasPermission(session,"tables.write"))return reply({error:"forbidden",message:"You cannot change table status."},403);const body=await request.json(),allowed=["available","dirty","inactive"],status=body.status;if(!allowed.includes(status))return reply({error:"invalid_status"},400);const result=await env.DB.prepare("UPDATE cafe_tables SET operational_status=?,updated_at=? WHERE id=? AND id IN (SELECT t.id FROM cafe_tables t JOIN areas a ON a.id=t.area_id WHERE a.branch_id=?)").bind(status,new Date().toISOString(),decodeURIComponent(itemId),branch.id).run();return result.meta?.changes?reply({id:decodeURIComponent(itemId),status}):reply({error:"table_not_found"},404)}
      return reply({error:"method_not_allowed"},405)
    }
    const imageMatch=url.pathname.match(/^\/api\/cafes\/([^/]+)\/branches\/([^/]+)\/map\/analyze$/);if(imageMatch){const [,cafeSlug,branchSlug]=imageMatch;if(!["GET","POST"].includes(request.method))return reply({error:"method_not_allowed"},405);if(!safeSlug(cafeSlug)||!safeSlug(branchSlug))return reply({error:"invalid_slug"},400);const branch=await branchRow(env.DB,cafeSlug,branchSlug),session=await sessionStaff(env.DB,request);if(!branch||!session||!canUseBranch(session,branch)||!hasPermission(session,"map.write"))return reply({error:"forbidden",message:"You cannot edit this branch map."},403);return request.method==="GET"?reply({enabled:Boolean(env.OPENAI_API_KEY)}):analyzeMapImage(request,env)}
    const branchMatch=url.pathname.match(/^\/api\/cafes\/([^/]+)\/branches\/([^/]+)\/(map|settings|schedule|availability|reservations)$/);if(branchMatch){const [,cafeSlug,branchSlug,resource]=branchMatch;if(request.method==="PUT"||resource==="reservations"&&request.method==="GET"){const branch=await branchRow(env.DB,cafeSlug,branchSlug),session=await sessionStaff(env.DB,request),needed=request.method==="PUT"?`${resource}.write`:"reservations.read";if(!session||!branch||!canUseBranch(session,branch)||!hasPermission(session,needed))return reply({error:"forbidden",message:"Access denied."},403)}return handleBranchApi(request,env,url,cafeSlug,branchSlug,resource)}
    const reservationMatch=url.pathname.match(/^\/api\/reservations\/([A-Z0-9-]+)(?:\/(cancel|pay))?$/);
    if(reservationMatch){const code=reservationMatch[1],action=reservationMatch[2];if(request.method==="GET"&&!action){const row=await lookupReservation(env.DB,code,url.searchParams.get("mobile"));return row?reply(publicReservation(row)):reply({error:"reservation_not_found",message:"No booking matches those details."},404)}const body=await request.json(),row=await lookupReservation(env.DB,code,body.mobile);if(!row)return reply({error:"reservation_not_found",message:"No booking matches those details."},404);if(action==="pay"&&request.method==="POST")return payReservationDemo(env,row);if(action==="cancel"&&request.method==="POST"){if(["completed","cancelled","no_show"].includes(row.status))return reply({error:"cannot_cancel",message:"This booking cannot be cancelled."},409);await env.DB.batch([env.DB.prepare("UPDATE reservations SET status='cancelled',updated_at=? WHERE id=?").bind(new Date().toISOString(),row.id),env.DB.prepare("DELETE FROM reservation_locks WHERE reservation_id=?").bind(row.id),env.DB.prepare("UPDATE sms_messages SET status='cancelled' WHERE reservation_id=? AND kind='reminder' AND status='queued'").bind(row.id)]);return reply({...publicReservation(row),status:"cancelled"})}if(!action&&request.method==="PATCH"){const allowed=["pending","confirmed","arrived","completed","cancelled","no_show"],status=body.status;if(!allowed.includes(status))return reply({error:"invalid_status"},400);const statements=[env.DB.prepare("UPDATE reservations SET status=?,updated_at=? WHERE id=?").bind(status,new Date().toISOString(),row.id)];if(["cancelled","no_show","completed"].includes(status)){statements.push(env.DB.prepare("DELETE FROM reservation_locks WHERE reservation_id=?").bind(row.id));statements.push(env.DB.prepare("UPDATE sms_messages SET status='cancelled' WHERE reservation_id=? AND kind='reminder' AND status='queued'").bind(row.id))}await env.DB.batch(statements);return reply({...publicReservation(row),status})}}
    return reply({error:"not_found"},404)
  }catch(error){console.error("api_error",error);return reply({error:"database_temporarily_unavailable",message:"Database connection failed. Try again."},503)}
}

export default {async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname.startsWith("/api/")){if(request.method==="GET"&&url.pathname.startsWith("/api/cafes/")){ctx.waitUntil(processDueReminders(env));ctx.waitUntil(expireUnpaidReservations(env.DB))}return handleApi(request,env,url)}if(url.pathname==="/saas-admin"){if(!env.DB||!await requireSaasAdmin(env.DB,request))return new Response("Access denied.",{status:403,headers:{"content-type":"text/plain; charset=utf-8","cache-control":"no-store"}});return new Response(saasPage,{headers:{"content-type":textTypes["/saas-admin"],"cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}})}if(url.pathname==="/assets/cafe-hero.webp")return new Response(decodeBase64(heroBase64),{headers:{"content-type":"image/webp","cache-control":"public, max-age=604800"}});const content=url.pathname==="/"||url.pathname==="/index.html"?page:url.pathname==="/styles.css"?stylesCss:url.pathname==="/editor.css"?editorCss:url.pathname==="/app.js"?appJs:url.pathname==="/saas-admin.css"?saasCss:url.pathname==="/saas-admin.js"?saasJs:null;if(content===null)return new Response("Not found",{status:404});return new Response(content,{headers:{"content-type":textTypes[url.pathname]||textTypes["/"],"x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin"}})},async scheduled(controller,env,ctx){void controller;ctx.waitUntil(Promise.all([processDueReminders(env),expireUnpaidReservations(env.DB)]))}};
