import { wireModal } from "./modal.js";
import { wireJalaliPicker } from "./jalali-picker.js";
import { wireBooking } from "./booking.js";
import { wireReservationForm } from "./reservation-form.js";
import { wireTracking } from "./tracking.js";
import { wireManager } from "./manager.js";
import { wireBranches } from "./branches.js";
import { wireStaff } from "./staff.js";
import { wireSms } from "./sms.js";
import { wireSubscription } from "./subscription.js";
import { wireReports } from "./reports.js";
import { wireLoyalty } from "./loyalty.js";
import { wireEditorNav } from "./editor-nav.js";
import { wireMapImport } from "./map-import.js";
import { wireEditor } from "./editor.js";
import { wireControls } from "./controls.js";
import { wireSchedule } from "./schedule.js";
import { wireOperations } from "./operations.js";
import { wirePayments } from "./payments.js";
import { wireFloorEditorTools } from "./floor/editor-tools.js";
import { wireFloorZoom } from "./floor/zoom.js";
import { initializeApp } from "./init.js";

wireModal();
wireJalaliPicker();
wireBooking();
wireReservationForm();
wireTracking();
wireManager();
wireBranches();
wireStaff();
wireSms();
wireSubscription();
wireReports();
wireLoyalty();
wireEditorNav();
wireMapImport();
wireEditor();
wireControls();
wireSchedule();
wireOperations();
wirePayments();
wireFloorEditorTools();
wireFloorZoom();

initializeApp();
