const faDigits=value=>new Intl.NumberFormat('fa-IR').format(Number(value||0));
const formatToman=rials=>`${new Intl.NumberFormat('fa-IR').format(Math.round(Number(rials||0)/10))} tomans`;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let saasData=null;
function renderSaas(){document.querySelector('#saasCafeCount').textContent=faDigits(saasData.stats.cafes);document.querySelector('#saasEnabledCount').textContent=faDigits(saasData.stats.enabled);document.querySelector('#saasTrialCount').textContent=faDigits(saasData.stats.trials);document.querySelector('#saasActiveCount').textContent=faDigits(saasData.stats.active);document.querySelector('#saasMrr').textContent=formatToman(saasData.stats.mrrRials);const list=document.querySelector('#saasCafeList');list.innerHTML='';if(!saasData.cafes.length){list.innerHTML='<div class="saas-empty">No cafés have been set up yet.</div>';return}saasData.cafes.forEach(cafe=>{const row=document.createElement('article');row.className='saas-cafe-row';row.innerHTML=`<div class="saas-cafe-name"><span>${escapeHtml(cafe.name.trim().charAt(0)||'C')}</span><div><h3>${escapeHtml(cafe.name)}</h3><p>${faDigits(cafe.branchCount)} Active locations · ${cafe.enabled?'Subscriptions enabled':'No subscription'}</p></div></div><div class="saas-price"><span>Monthly cost</span><b>${formatToman(cafe.monthlyPriceRials)}</b></div><label>Status<select class="saas-status"><option value="inactive" ${cafe.status==='inactive'?'selected':''}>Inactive</option><option value="trial" ${cafe.status==='trial'?'selected':''}>Demo</option><option value="active" ${cafe.status==='active'?'selected':''}>Active</option><option value="past_due" ${cafe.status==='past_due'?'selected':''}>Payment due</option></select></label><label class="saas-enabled">Subscriptions enabled<input type="checkbox" ${cafe.enabled?'checked':''}></label><button class="saas-save">Save</button>`;row.querySelector('.saas-save').onclick=()=>saveSaasCafe(cafe.id,row);list.appendChild(row)})}
async function fetchSaas(){const error=document.querySelector('#saasError'),button=document.querySelector('#refreshSaas');error.textContent='';button.disabled=true;try{const response=await fetch('/api/saas/overview'),data=await response.json();if(!response.ok)throw new Error(data.message||'Could not load data.');saasData=data;renderSaas()}catch(err){error.textContent=err.message;document.querySelector('#saasCafeList').innerHTML='<div class="saas-empty">You cannot access this data.</div>'}finally{button.disabled=false}}
async function saveSaasCafe(cafeId,row){const button=row.querySelector('.saas-save'),error=document.querySelector('#saasError');button.disabled=true;error.textContent='';try{const response=await fetch('/api/saas/overview',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({cafeId,status:row.querySelector('.saas-status').value,enabled:row.querySelector('.saas-enabled input').checked})}),data=await response.json();if(!response.ok)throw new Error(data.message||'Could not save account.');saasData=data;renderSaas()}catch(err){error.textContent=err.message;button.disabled=false}}
document.querySelector('#refreshSaas').onclick=fetchSaas;
fetchSaas();
